from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass


FINRA_SHORT_INTEREST_SCIENTIFIC_CONTRACT = (
    "alpha-gate-finra-short-interest-scientific-v1-four-position-change-crowding-buckets"
)
FINRA_SHORT_INTEREST_SCIENTIFIC_FINGERPRINT = (
    "0b32d59677e86544777807525cd4aba13dd36fd0fcfd7744458556205561d13f"
)
FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_CONTRACT = (
    "alpha-gate-finra-short-interest-pit-audit-v1-publication-revision-split-active-common-stock-no-market-outcomes"
)
FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_FINGERPRINT = (
    "ffdb7389ceae73f31a3781a79a8d825338102b9084cb30dd03bf21f6bf003846"
)
FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_TARGET_HEAD = (
    "db1af342ba4481360bf429ad696b5c7870b20f73"
)
FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_STATUS = "PIT_AUDIT_PASS"
FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_REPORT_SHA256 = (
    "4fb3abc3e561fd4187efbf60967127230f14d37204d21b5ccb910c40a4469845"
)
FINRA_SHORT_INTEREST_ENTRY_PIT_EVIDENCE = {
    "immutable_exchange_listed_rows": 136_731,
    "pit_eligible_rows": 63_761,
    "unique_pit_instruments": 8_054,
    "files_with_2500_pit_rows": 12,
    "target_outcome_rows_read": 0,
    "protected_return_rows_read": 0,
    "protected_holdout_consumed": False,
}

FINRA_SHORT_INTEREST_MECHANISM = (
    "PIT_FINRA_CONSOLIDATED_SHORT_INTEREST_POSITIONING_AND_CROWDING"
)
FINRA_SHORT_INTEREST_SOURCE_SETTLEMENT_START = "2021-06-30"
FINRA_SHORT_INTEREST_SOURCE_SETTLEMENT_CUTOFF = "2026-04-15"
FINRA_SHORT_INTEREST_SETTLEMENT_SCHEDULE_RULE = (
    "FINRA_TWICE_MONTHLY_PREVIOUS_XNYS_ON_OR_BEFORE_15TH_AND_LAST_XNYS_SESSION_OF_MONTH"
)
FINRA_SHORT_INTEREST_PUBLICATION_RULE = (
    "SEVENTH_XNYS_SESSION_AFTER_SETTLEMENT_AVAILABLE_BY_16_40_ET"
)
FINRA_SHORT_INTEREST_DECISION_RULE = (
    "FIRST_XNYS_SESSION_OPEN_STRICTLY_AFTER_PUBLICATION_DATE"
)
FINRA_SHORT_INTEREST_IDENTITY_RULE = (
    "EXACT_FINRA_SYMBOL_PRIMARY_EXCHANGE_ACTIVE_CS_AT_SETTLEMENT_AND_DECISION_"
    "SAME_STRONG_OR_MEDIUM_INSTRUMENT_ID"
)
FINRA_SHORT_INTEREST_REVISION_RULE = "EXCLUDE_ANY_NONBLANK_REVISION_FLAG"
FINRA_SHORT_INTEREST_STOCK_SPLIT_SOURCE_RULE = (
    "EXCLUDE_ANY_NONBLANK_STOCK_SPLIT_FLAG_FROM_PREDICTOR_ELIGIBILITY"
)

FINRA_SHORT_INTEREST_PERFORMANCE_SIGNAL_START = "2021-08-16"
FINRA_SHORT_INTEREST_DEVELOPMENT_LAST_SIGNAL = "2024-12-31"
FINRA_SHORT_INTEREST_OUTER_EMBARGO_START = "2025-01-02"
FINRA_SHORT_INTEREST_OUTER_EMBARGO_END = "2025-04-03"
FINRA_SHORT_INTEREST_PROTECTED_START = "2025-04-04"
FINRA_SHORT_INTEREST_PROTECTED_LAST_SIGNAL = "2026-05-11"
FINRA_SHORT_INTEREST_PROTECTED_OUTCOME_END = "2026-08-11"

FINRA_SHORT_INTEREST_PREDICTOR_READY_RULE = (
    "PIT_ELIGIBLE_AND_PREVIOUS_SHORT_PRESENT_AND_FINITE_DAYS_TO_COVER_GT_0"
)
FINRA_SHORT_INTEREST_POSITION_CHANGE_FEATURE = (
    "LN((CURRENT_SHORT+1)/(PREVIOUS_SHORT+1))"
)
FINRA_SHORT_INTEREST_CROSS_SECTION_RANK_RULE = (
    "WITHIN_SETTLEMENT_AVERAGE_TIE_PERCENTILE_(AVG_RANK_MINUS_1)/(N_MINUS_1)"
)
FINRA_SHORT_INTEREST_COVER_PERCENTILE_MAX = 0.10
FINRA_SHORT_INTEREST_BUILD_PERCENTILE_MIN = 0.90
FINRA_SHORT_INTEREST_CROWDED_PERCENTILE_MIN = 0.80


@dataclass(frozen=True, slots=True)
class FINRAShortInterestHypothesisSpec:
    candidate_id: str
    direction: str
    change_rule: str
    crowding_rule: str


FINRA_SHORT_INTEREST_HYPOTHESES = (
    FINRAShortInterestHypothesisSpec(
        "rapid_short_build_crowded_short",
        "SHORT",
        "change_percentile>=0.90",
        "crowding_percentile>=0.80",
    ),
    FINRAShortInterestHypothesisSpec(
        "rapid_short_build_non_crowded_short",
        "SHORT",
        "change_percentile>=0.90",
        "crowding_percentile<0.80",
    ),
    FINRAShortInterestHypothesisSpec(
        "rapid_short_cover_crowded_long",
        "LONG",
        "change_percentile<=0.10",
        "crowding_percentile>=0.80",
    ),
    FINRAShortInterestHypothesisSpec(
        "rapid_short_cover_non_crowded_long",
        "LONG",
        "change_percentile<=0.10",
        "crowding_percentile<0.80",
    ),
)

FINRA_SHORT_INTEREST_MAX_ROWS_PER_CANDIDATE_PER_SETTLEMENT = 75
FINRA_SHORT_INTEREST_SOURCE_SAMPLE_RULE = (
    "SHA256_CANDIDATE_INSTRUMENT_SETTLEMENT_SCIENTIFIC_FINGERPRINT_ASCENDING"
)
FINRA_SHORT_INTEREST_SOURCE_SAMPLE_MARKET_OUTCOME_INDEPENDENT = True

FINRA_SHORT_INTEREST_ENTRY_RULE = "DECISION_SESSION_OPEN"
FINRA_SHORT_INTEREST_EXIT_RULE = "CLOSE_63_XNYS_SESSIONS_AFTER_DECISION"
FINRA_SHORT_INTEREST_PRIMARY_HORIZON_SESSIONS = 63
FINRA_SHORT_INTEREST_DIAGNOSTIC_HORIZONS_SESSIONS = (21, 126)
FINRA_SHORT_INTEREST_BENCHMARK = "SPY"
FINRA_SHORT_INTEREST_PRIMARY_RETURN = (
    "direction*(stock_open_to_t63_close_return-SPY_open_to_t63_close_return)"
    "-direction_specific_cost"
)
FINRA_SHORT_INTEREST_UNHEDGED_RETURN = (
    "direction*stock_open_to_t63_close_return-direction_specific_cost"
)
FINRA_SHORT_INTEREST_PRIMARY_COST_BPS = {"LONG": 10.0, "SHORT": 35.0}
FINRA_SHORT_INTEREST_STRESS_COST_BPS = {"LONG": 25.0, "SHORT": 100.0}
FINRA_SHORT_INTEREST_SHORT_BORROW_ASSUMPTION = (
    "PRIMARY_100_BPS_ANNUALIZED_PLUS_EXECUTION;"
    "STRESS_300_BPS_ANNUALIZED_PLUS_EXECUTION"
)
FINRA_SHORT_INTEREST_PATH_RULE = (
    "EXACT_ENTRY_OPEN_AND_EXIT_CLOSE_REQUIRED;CENSOR_ANY_SPLIT_CROSSING_PATH"
)

FINRA_SHORT_INTEREST_DEVELOPMENT_SELECTION_FRACTION = 0.70
FINRA_SHORT_INTEREST_INTERNAL_PURGE_SESSIONS = 63
FINRA_SHORT_INTEREST_SELECTION_FOLDS = 4
FINRA_SHORT_INTEREST_INTERNAL_VALIDATION_FOLDS = 3
FINRA_SHORT_INTEREST_PROTECTED_FOLDS = 4
FINRA_SHORT_INTEREST_BOOTSTRAP_BLOCK_SESSIONS = 63
FINRA_SHORT_INTEREST_BOOTSTRAP_REPLICATES = 2_000
FINRA_SHORT_INTEREST_BOOTSTRAP_SEED = 456_033
FINRA_SHORT_INTEREST_SELECTION_CONFIDENCE = 0.95
FINRA_SHORT_INTEREST_INTERNAL_CONFIDENCE = 0.90
FINRA_SHORT_INTEREST_PROTECTED_CONFIDENCE = 0.80

FINRA_SHORT_INTEREST_SELECTION_MIN_EVENT_ROWS = 900
FINRA_SHORT_INTEREST_SELECTION_MIN_SIGNAL_SESSIONS = 30
FINRA_SHORT_INTEREST_SELECTION_MIN_UNIQUE_INSTRUMENTS = 500
FINRA_SHORT_INTEREST_SELECTION_MIN_POSITIVE_FOLDS = 3
FINRA_SHORT_INTEREST_INTERNAL_MIN_EVENT_ROWS = 250
FINRA_SHORT_INTEREST_INTERNAL_MIN_SIGNAL_SESSIONS = 12
FINRA_SHORT_INTEREST_INTERNAL_MIN_UNIQUE_INSTRUMENTS = 150
FINRA_SHORT_INTEREST_INTERNAL_MIN_POSITIVE_FOLDS = 2
FINRA_SHORT_INTEREST_PROTECTED_MIN_EVENT_ROWS = 300
FINRA_SHORT_INTEREST_PROTECTED_MIN_SIGNAL_SESSIONS = 16
FINRA_SHORT_INTEREST_PROTECTED_MIN_UNIQUE_INSTRUMENTS = 200
FINRA_SHORT_INTEREST_PROTECTED_MIN_POSITIVE_FOLDS = 3
FINRA_SHORT_INTEREST_MIN_POSITIVE_YEAR_FRACTION = 0.60
FINRA_SHORT_INTEREST_MIN_YEAR_SIGNAL_SESSIONS = 8
FINRA_SHORT_INTEREST_MAX_SINGLE_SESSION_ROW_FRACTION = 0.05
FINRA_SHORT_INTEREST_MAX_SINGLE_INSTRUMENT_ROW_FRACTION = 0.02

FINRA_SHORT_INTEREST_MULTIPLE_TESTING_METHOD = "HOLM_BONFERRONI_GLOBAL_4"
FINRA_SHORT_INTEREST_MULTIPLE_TESTING_ALPHA = 0.05
FINRA_SHORT_INTEREST_SELECTION_WINNER_RULE = (
    "highest_primary_selection_LCB_then_candidate_id_within_direction"
)
FINRA_SHORT_INTEREST_MAX_SELECTION_WINNERS_PER_DIRECTION = 1
FINRA_SHORT_INTEREST_MAX_FINALISTS_PER_DIRECTION = 1
FINRA_SHORT_INTEREST_RUNNER_UP_SUBSTITUTION_ALLOWED = False
FINRA_SHORT_INTEREST_PRIMARY_MEAN_POSITIVE_REQUIRED = True
FINRA_SHORT_INTEREST_PRIMARY_LCB_POSITIVE_REQUIRED = True
FINRA_SHORT_INTEREST_STRESS_MEAN_POSITIVE_REQUIRED = True
FINRA_SHORT_INTEREST_UNHEDGED_PRIMARY_MEAN_POSITIVE_REQUIRED = True
FINRA_SHORT_INTEREST_DEFLATED_PERFORMANCE_DIAGNOSTIC_REQUIRED = True

FINRA_SHORT_INTEREST_PROTECTED_SOURCE_ONLY_PRECHECK_REQUIRED = True
FINRA_SHORT_INTEREST_PROTECTED_RETURNS_BEFORE_FINALISTS_ALLOWED = False
FINRA_SHORT_INTEREST_PROTECTED_PREDICTORS_BEFORE_FINALISTS_ALLOWED = True
FINRA_SHORT_INTEREST_PROTECTED_HOLDOUT_CONSUMED_AFTER_ANY_NONEMPTY_RETURN_READ = True
FINRA_SHORT_INTEREST_PROVIDER_WRITES = 0
FINRA_SHORT_INTEREST_BROKER_READS = 0
FINRA_SHORT_INTEREST_BROKER_WRITES = 0
FINRA_SHORT_INTEREST_ORDER_WRITES = 0
FINRA_SHORT_INTEREST_PAPER_SUBMITS = 0
FINRA_SHORT_INTEREST_LIVE_WRITES = 0
FINRA_SHORT_INTEREST_AUTOMATION_WRITES = 0
FINRA_SHORT_INTEREST_AUTOMATIC_BROKER_FAILOVER = False
FINRA_SHORT_INTEREST_PHASE33_SIGNAL_TO_TRADE_AUTHORITY = False


def _policy_payload() -> dict[str, object]:
    return {
        "contract_version": FINRA_SHORT_INTEREST_SCIENTIFIC_CONTRACT,
        "entry_pit_audit_contract": FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_CONTRACT,
        "entry_pit_audit_fingerprint": FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_FINGERPRINT,
        "entry_pit_audit_target_head": FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_TARGET_HEAD,
        "entry_pit_audit_status": FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_STATUS,
        "entry_pit_audit_report_sha256": FINRA_SHORT_INTEREST_ENTRY_PIT_AUDIT_REPORT_SHA256,
        "entry_pit_evidence": dict(FINRA_SHORT_INTEREST_ENTRY_PIT_EVIDENCE),
        "mechanism": FINRA_SHORT_INTEREST_MECHANISM,
        "source_settlement_start": FINRA_SHORT_INTEREST_SOURCE_SETTLEMENT_START,
        "source_settlement_cutoff": FINRA_SHORT_INTEREST_SOURCE_SETTLEMENT_CUTOFF,
        "settlement_schedule_rule": FINRA_SHORT_INTEREST_SETTLEMENT_SCHEDULE_RULE,
        "publication_rule": FINRA_SHORT_INTEREST_PUBLICATION_RULE,
        "decision_rule": FINRA_SHORT_INTEREST_DECISION_RULE,
        "identity_rule": FINRA_SHORT_INTEREST_IDENTITY_RULE,
        "revision_rule": FINRA_SHORT_INTEREST_REVISION_RULE,
        "stock_split_source_rule": FINRA_SHORT_INTEREST_STOCK_SPLIT_SOURCE_RULE,
        "performance_signal_start": FINRA_SHORT_INTEREST_PERFORMANCE_SIGNAL_START,
        "development_last_signal": FINRA_SHORT_INTEREST_DEVELOPMENT_LAST_SIGNAL,
        "outer_embargo_start": FINRA_SHORT_INTEREST_OUTER_EMBARGO_START,
        "outer_embargo_end": FINRA_SHORT_INTEREST_OUTER_EMBARGO_END,
        "protected_start": FINRA_SHORT_INTEREST_PROTECTED_START,
        "protected_last_signal": FINRA_SHORT_INTEREST_PROTECTED_LAST_SIGNAL,
        "protected_outcome_end": FINRA_SHORT_INTEREST_PROTECTED_OUTCOME_END,
        "predictor_ready_rule": FINRA_SHORT_INTEREST_PREDICTOR_READY_RULE,
        "position_change_feature": FINRA_SHORT_INTEREST_POSITION_CHANGE_FEATURE,
        "cross_section_rank_rule": FINRA_SHORT_INTEREST_CROSS_SECTION_RANK_RULE,
        "change_tail_thresholds": {
            "cover_lte": FINRA_SHORT_INTEREST_COVER_PERCENTILE_MAX,
            "build_gte": FINRA_SHORT_INTEREST_BUILD_PERCENTILE_MIN,
        },
        "crowding_threshold": {
            "crowded_gte": FINRA_SHORT_INTEREST_CROWDED_PERCENTILE_MIN,
            "non_crowded_lt": FINRA_SHORT_INTEREST_CROWDED_PERCENTILE_MIN,
        },
        "hypotheses": [asdict(spec) for spec in FINRA_SHORT_INTEREST_HYPOTHESES],
        "source_sampling": {
            "max_rows_per_candidate_per_settlement": FINRA_SHORT_INTEREST_MAX_ROWS_PER_CANDIDATE_PER_SETTLEMENT,
            "rule": FINRA_SHORT_INTEREST_SOURCE_SAMPLE_RULE,
            "market_outcome_independent": FINRA_SHORT_INTEREST_SOURCE_SAMPLE_MARKET_OUTCOME_INDEPENDENT,
        },
        "entry_rule": FINRA_SHORT_INTEREST_ENTRY_RULE,
        "exit_rule": FINRA_SHORT_INTEREST_EXIT_RULE,
        "primary_horizon_sessions": FINRA_SHORT_INTEREST_PRIMARY_HORIZON_SESSIONS,
        "diagnostic_horizons_sessions": list(FINRA_SHORT_INTEREST_DIAGNOSTIC_HORIZONS_SESSIONS),
        "benchmark": FINRA_SHORT_INTEREST_BENCHMARK,
        "primary_return": FINRA_SHORT_INTEREST_PRIMARY_RETURN,
        "unhedged_return": FINRA_SHORT_INTEREST_UNHEDGED_RETURN,
        "primary_cost_bps": dict(FINRA_SHORT_INTEREST_PRIMARY_COST_BPS),
        "stress_cost_bps": dict(FINRA_SHORT_INTEREST_STRESS_COST_BPS),
        "short_borrow_assumption": FINRA_SHORT_INTEREST_SHORT_BORROW_ASSUMPTION,
        "path_rule": FINRA_SHORT_INTEREST_PATH_RULE,
        "development_selection_fraction": FINRA_SHORT_INTEREST_DEVELOPMENT_SELECTION_FRACTION,
        "internal_purge_sessions": FINRA_SHORT_INTEREST_INTERNAL_PURGE_SESSIONS,
        "selection_folds": FINRA_SHORT_INTEREST_SELECTION_FOLDS,
        "internal_validation_folds": FINRA_SHORT_INTEREST_INTERNAL_VALIDATION_FOLDS,
        "protected_folds": FINRA_SHORT_INTEREST_PROTECTED_FOLDS,
        "bootstrap_block_sessions": FINRA_SHORT_INTEREST_BOOTSTRAP_BLOCK_SESSIONS,
        "bootstrap_replicates": FINRA_SHORT_INTEREST_BOOTSTRAP_REPLICATES,
        "bootstrap_seed": FINRA_SHORT_INTEREST_BOOTSTRAP_SEED,
        "selection_confidence": FINRA_SHORT_INTEREST_SELECTION_CONFIDENCE,
        "internal_confidence": FINRA_SHORT_INTEREST_INTERNAL_CONFIDENCE,
        "protected_confidence": FINRA_SHORT_INTEREST_PROTECTED_CONFIDENCE,
        "selection_min_event_rows": FINRA_SHORT_INTEREST_SELECTION_MIN_EVENT_ROWS,
        "selection_min_signal_sessions": FINRA_SHORT_INTEREST_SELECTION_MIN_SIGNAL_SESSIONS,
        "selection_min_unique_instruments": FINRA_SHORT_INTEREST_SELECTION_MIN_UNIQUE_INSTRUMENTS,
        "selection_min_positive_folds": FINRA_SHORT_INTEREST_SELECTION_MIN_POSITIVE_FOLDS,
        "internal_min_event_rows": FINRA_SHORT_INTEREST_INTERNAL_MIN_EVENT_ROWS,
        "internal_min_signal_sessions": FINRA_SHORT_INTEREST_INTERNAL_MIN_SIGNAL_SESSIONS,
        "internal_min_unique_instruments": FINRA_SHORT_INTEREST_INTERNAL_MIN_UNIQUE_INSTRUMENTS,
        "internal_min_positive_folds": FINRA_SHORT_INTEREST_INTERNAL_MIN_POSITIVE_FOLDS,
        "protected_min_event_rows": FINRA_SHORT_INTEREST_PROTECTED_MIN_EVENT_ROWS,
        "protected_min_signal_sessions": FINRA_SHORT_INTEREST_PROTECTED_MIN_SIGNAL_SESSIONS,
        "protected_min_unique_instruments": FINRA_SHORT_INTEREST_PROTECTED_MIN_UNIQUE_INSTRUMENTS,
        "protected_min_positive_folds": FINRA_SHORT_INTEREST_PROTECTED_MIN_POSITIVE_FOLDS,
        "min_positive_year_fraction": FINRA_SHORT_INTEREST_MIN_POSITIVE_YEAR_FRACTION,
        "min_year_signal_sessions": FINRA_SHORT_INTEREST_MIN_YEAR_SIGNAL_SESSIONS,
        "max_single_session_row_fraction": FINRA_SHORT_INTEREST_MAX_SINGLE_SESSION_ROW_FRACTION,
        "max_single_instrument_row_fraction": FINRA_SHORT_INTEREST_MAX_SINGLE_INSTRUMENT_ROW_FRACTION,
        "multiple_testing_method": FINRA_SHORT_INTEREST_MULTIPLE_TESTING_METHOD,
        "multiple_testing_alpha": FINRA_SHORT_INTEREST_MULTIPLE_TESTING_ALPHA,
        "selection_winner_rule": FINRA_SHORT_INTEREST_SELECTION_WINNER_RULE,
        "max_selection_winners_per_direction": FINRA_SHORT_INTEREST_MAX_SELECTION_WINNERS_PER_DIRECTION,
        "max_finalists_per_direction": FINRA_SHORT_INTEREST_MAX_FINALISTS_PER_DIRECTION,
        "runner_up_substitution_allowed": FINRA_SHORT_INTEREST_RUNNER_UP_SUBSTITUTION_ALLOWED,
        "primary_mean_positive_required": FINRA_SHORT_INTEREST_PRIMARY_MEAN_POSITIVE_REQUIRED,
        "primary_lcb_positive_required": FINRA_SHORT_INTEREST_PRIMARY_LCB_POSITIVE_REQUIRED,
        "stress_mean_positive_required": FINRA_SHORT_INTEREST_STRESS_MEAN_POSITIVE_REQUIRED,
        "unhedged_primary_mean_positive_required": FINRA_SHORT_INTEREST_UNHEDGED_PRIMARY_MEAN_POSITIVE_REQUIRED,
        "deflated_performance_diagnostic_required": FINRA_SHORT_INTEREST_DEFLATED_PERFORMANCE_DIAGNOSTIC_REQUIRED,
        "protected_source_only_precheck_required": FINRA_SHORT_INTEREST_PROTECTED_SOURCE_ONLY_PRECHECK_REQUIRED,
        "protected_returns_before_finalists_allowed": FINRA_SHORT_INTEREST_PROTECTED_RETURNS_BEFORE_FINALISTS_ALLOWED,
        "protected_predictors_before_finalists_allowed": FINRA_SHORT_INTEREST_PROTECTED_PREDICTORS_BEFORE_FINALISTS_ALLOWED,
        "protected_holdout_consumed_after_any_nonempty_return_read": FINRA_SHORT_INTEREST_PROTECTED_HOLDOUT_CONSUMED_AFTER_ANY_NONEMPTY_RETURN_READ,
        "provider_writes": FINRA_SHORT_INTEREST_PROVIDER_WRITES,
        "broker_reads": FINRA_SHORT_INTEREST_BROKER_READS,
        "broker_writes": FINRA_SHORT_INTEREST_BROKER_WRITES,
        "order_writes": FINRA_SHORT_INTEREST_ORDER_WRITES,
        "paper_submits": FINRA_SHORT_INTEREST_PAPER_SUBMITS,
        "live_writes": FINRA_SHORT_INTEREST_LIVE_WRITES,
        "automation_writes": FINRA_SHORT_INTEREST_AUTOMATION_WRITES,
        "automatic_broker_failover": FINRA_SHORT_INTEREST_AUTOMATIC_BROKER_FAILOVER,
        "phase33_signal_to_trade_authority": FINRA_SHORT_INTEREST_PHASE33_SIGNAL_TO_TRADE_AUTHORITY,
    }


def finra_short_interest_scientific_fingerprint() -> str:
    encoded = json.dumps(
        _policy_payload(), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


if finra_short_interest_scientific_fingerprint() != FINRA_SHORT_INTEREST_SCIENTIFIC_FINGERPRINT:
    raise RuntimeError("FINRA short-interest scientific policy fingerprint drifted")
