from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass


BENEFICIAL_OWNERSHIP_SCIENTIFIC_CONTRACT = (
    "alpha-gate-beneficial-ownership-scientific-v1-four-initial-ownership-intent-buckets"
)
BENEFICIAL_OWNERSHIP_SCIENTIFIC_FINGERPRINT = (
    "4bf51f02fb74a219609e2affef3319b24b7c98eb06fa9d88e405ae4f7448434c"
)
BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_CONTRACT = (
    "alpha-gate-sec-beneficial-ownership-source-repair-v2-master-index-role-bounded-index-size-no-market-outcomes"
)
BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_FINGERPRINT = (
    "78bf3f18368114a5a6073e8a4d66a0c13ee29a5da78b8adeb1d71b1f10c6f78c"
)
BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_STATUS = "FEASIBILITY_PASS"
BENEFICIAL_OWNERSHIP_ENTRY_QUARTER_INDEXES = 43
BENEFICIAL_OWNERSHIP_ENTRY_SUBMISSION_SUCCESS = 200
BENEFICIAL_OWNERSHIP_ENTRY_UNIQUE_SUBJECT_CIKS = 195
BENEFICIAL_OWNERSHIP_ENTRY_UNAMBIGUOUS_MAPPINGS = 142

BENEFICIAL_OWNERSHIP_MECHANISM = (
    "PIT_SEC_SCHEDULE_13D_13G_INITIAL_BENEFICIAL_OWNERSHIP_INTENT_AND_CONCENTRATION"
)
BENEFICIAL_OWNERSHIP_SOURCE_START = "2016-01-01"
BENEFICIAL_OWNERSHIP_SOURCE_CUTOFF = "2026-08-11"
BENEFICIAL_OWNERSHIP_PERFORMANCE_SIGNAL_START = "2021-08-16"
BENEFICIAL_OWNERSHIP_DEVELOPMENT_LAST_SIGNAL = "2024-12-31"
BENEFICIAL_OWNERSHIP_OUTER_EMBARGO_START = "2025-01-02"
BENEFICIAL_OWNERSHIP_OUTER_EMBARGO_END = "2025-04-03"
BENEFICIAL_OWNERSHIP_PROTECTED_START = "2025-04-04"
BENEFICIAL_OWNERSHIP_PROTECTED_LAST_SIGNAL = "2026-05-11"
BENEFICIAL_OWNERSHIP_PROTECTED_OUTCOME_END = "2026-08-11"

BENEFICIAL_OWNERSHIP_ELIGIBLE_FORMS = (
    "SC 13D",
    "SCHEDULE 13D",
    "SC 13G",
    "SCHEDULE 13G",
)
BENEFICIAL_OWNERSHIP_AMENDMENTS_PERFORMANCE_ELIGIBLE = False
BENEFICIAL_OWNERSHIP_PERCENT_RULE = (
    "MAX_FINITE_COVER_PAGE_PERCENT_OF_CLASS_ACROSS_REPORTING_PERSONS_NO_SUMMATION"
)
BENEFICIAL_OWNERSHIP_PERCENT_VALID_RANGE = "0_LT_PERCENT_LE_100"
BENEFICIAL_OWNERSHIP_PERCENT_BINS = ("5<=pct<10", "pct>=10")
BENEFICIAL_OWNERSHIP_PUBLIC_AVAILABILITY_RULE = (
    "FIRST_XNYS_SESSION_OPEN_STRICTLY_AFTER_SEC_ACCEPTANCE"
)
BENEFICIAL_OWNERSHIP_INSTRUMENT_RULE = (
    "EXACT_HEADER_SUBJECT_CIK_DECISION_DATE_ACTIVE_TRUE_TYPE_CS_UNIQUE_STRONG_OR_MEDIUM"
)


@dataclass(frozen=True, slots=True)
class BeneficialOwnershipHypothesisSpec:
    candidate_id: str
    form_family: str
    direction: str
    percent_min: float
    percent_max_exclusive: float | None


BENEFICIAL_OWNERSHIP_HYPOTHESES = (
    BeneficialOwnershipHypothesisSpec(
        "initial_13d_5_to_10_long", "13D_INITIAL", "LONG", 5.0, 10.0
    ),
    BeneficialOwnershipHypothesisSpec(
        "initial_13d_10_plus_long", "13D_INITIAL", "LONG", 10.0, None
    ),
    BeneficialOwnershipHypothesisSpec(
        "initial_13g_5_to_10_long", "13G_INITIAL", "LONG", 5.0, 10.0
    ),
    BeneficialOwnershipHypothesisSpec(
        "initial_13g_10_plus_long", "13G_INITIAL", "LONG", 10.0, None
    ),
)

BENEFICIAL_OWNERSHIP_DEVELOPMENT_SAMPLE_PER_FORM_FAMILY = 2_000
BENEFICIAL_OWNERSHIP_PROTECTED_SAMPLE_PER_FORM_FAMILY = 600
BENEFICIAL_OWNERSHIP_SOURCE_SAMPLE_RULE = (
    "SHA256_ACCESSION_PLUS_CONTRACT_WITHIN_FORM_FAMILY_AND_STAGE_BY_MASTER_INDEX_FILING_DATE"
)
BENEFICIAL_OWNERSHIP_SOURCE_SAMPLE_MARKET_OUTCOME_INDEPENDENT = True

BENEFICIAL_OWNERSHIP_ENTRY_RULE = "DECISION_SESSION_OPEN"
BENEFICIAL_OWNERSHIP_EXIT_RULE = "CLOSE_63_XNYS_SESSIONS_AFTER_DECISION"
BENEFICIAL_OWNERSHIP_PRIMARY_HORIZON_SESSIONS = 63
BENEFICIAL_OWNERSHIP_DIAGNOSTIC_HORIZONS_SESSIONS = (21, 126)
BENEFICIAL_OWNERSHIP_BENCHMARK = "SPY"
BENEFICIAL_OWNERSHIP_PRIMARY_RETURN = (
    "stock_open_to_t63_close_return-SPY_open_to_t63_close_return-long_cost"
)
BENEFICIAL_OWNERSHIP_UNHEDGED_RETURN = "stock_open_to_t63_close_return-long_cost"
BENEFICIAL_OWNERSHIP_PRIMARY_COST_BPS = 10.0
BENEFICIAL_OWNERSHIP_STRESS_COST_BPS = 25.0

BENEFICIAL_OWNERSHIP_DEVELOPMENT_SELECTION_FRACTION = 0.70
BENEFICIAL_OWNERSHIP_INTERNAL_PURGE_SESSIONS = 63
BENEFICIAL_OWNERSHIP_SELECTION_FOLDS = 4
BENEFICIAL_OWNERSHIP_INTERNAL_VALIDATION_FOLDS = 3
BENEFICIAL_OWNERSHIP_PROTECTED_FOLDS = 4
BENEFICIAL_OWNERSHIP_BOOTSTRAP_BLOCK_SESSIONS = 63
BENEFICIAL_OWNERSHIP_BOOTSTRAP_REPLICATES = 2_000
BENEFICIAL_OWNERSHIP_BOOTSTRAP_SEED = 133_013
BENEFICIAL_OWNERSHIP_SELECTION_CONFIDENCE = 0.95
BENEFICIAL_OWNERSHIP_INTERNAL_CONFIDENCE = 0.90
BENEFICIAL_OWNERSHIP_PROTECTED_CONFIDENCE = 0.80

BENEFICIAL_OWNERSHIP_SELECTION_MIN_EVENT_ROWS = 200
BENEFICIAL_OWNERSHIP_SELECTION_MIN_SIGNAL_SESSIONS = 100
BENEFICIAL_OWNERSHIP_SELECTION_MIN_UNIQUE_INSTRUMENTS = 50
BENEFICIAL_OWNERSHIP_SELECTION_MIN_POSITIVE_FOLDS = 3
BENEFICIAL_OWNERSHIP_INTERNAL_MIN_EVENT_ROWS = 60
BENEFICIAL_OWNERSHIP_INTERNAL_MIN_SIGNAL_SESSIONS = 30
BENEFICIAL_OWNERSHIP_INTERNAL_MIN_UNIQUE_INSTRUMENTS = 20
BENEFICIAL_OWNERSHIP_INTERNAL_MIN_POSITIVE_FOLDS = 2
BENEFICIAL_OWNERSHIP_PROTECTED_MIN_EVENT_ROWS = 60
BENEFICIAL_OWNERSHIP_PROTECTED_MIN_SIGNAL_SESSIONS = 25
BENEFICIAL_OWNERSHIP_PROTECTED_MIN_UNIQUE_INSTRUMENTS = 25
BENEFICIAL_OWNERSHIP_PROTECTED_MIN_POSITIVE_FOLDS = 2
BENEFICIAL_OWNERSHIP_MIN_POSITIVE_YEAR_FRACTION = 0.60
BENEFICIAL_OWNERSHIP_MIN_YEAR_SIGNAL_SESSIONS = 15
BENEFICIAL_OWNERSHIP_MAX_SINGLE_SESSION_ROW_FRACTION = 0.08
BENEFICIAL_OWNERSHIP_MAX_SINGLE_INSTRUMENT_ROW_FRACTION = 0.04

BENEFICIAL_OWNERSHIP_MULTIPLE_TESTING_METHOD = "HOLM_BONFERRONI_GLOBAL_4"
BENEFICIAL_OWNERSHIP_MULTIPLE_TESTING_ALPHA = 0.05
BENEFICIAL_OWNERSHIP_SELECTION_WINNER_RULE = (
    "highest_primary_selection_LCB_then_candidate_id"
)
BENEFICIAL_OWNERSHIP_MAX_SELECTION_WINNERS = 1
BENEFICIAL_OWNERSHIP_MAX_FINALISTS = 1
BENEFICIAL_OWNERSHIP_RUNNER_UP_SUBSTITUTION_ALLOWED = False
BENEFICIAL_OWNERSHIP_PRIMARY_MEAN_POSITIVE_REQUIRED = True
BENEFICIAL_OWNERSHIP_PRIMARY_LCB_POSITIVE_REQUIRED = True
BENEFICIAL_OWNERSHIP_STRESS_MEAN_POSITIVE_REQUIRED = True
BENEFICIAL_OWNERSHIP_UNHEDGED_PRIMARY_MEAN_POSITIVE_REQUIRED = True
BENEFICIAL_OWNERSHIP_REGULATORY_ERA_DIAGNOSTIC = (
    "PRE_2024_02_05_VS_POST_2024_02_05_DEADLINE_REGIME"
)
BENEFICIAL_OWNERSHIP_DEFLATED_PERFORMANCE_DIAGNOSTIC_REQUIRED = True

BENEFICIAL_OWNERSHIP_PROTECTED_SOURCE_ONLY_PRECHECK_REQUIRED = True
BENEFICIAL_OWNERSHIP_PROTECTED_RETURNS_BEFORE_FINALIST_ALLOWED = False
BENEFICIAL_OWNERSHIP_PROTECTED_PREDICTORS_BEFORE_FINALIST_ALLOWED = True
BENEFICIAL_OWNERSHIP_PROTECTED_HOLDOUT_CONSUMED_AFTER_ANY_NONEMPTY_RETURN_READ = True
BENEFICIAL_OWNERSHIP_PROVIDER_WRITES = 0
BENEFICIAL_OWNERSHIP_BROKER_READS = 0
BENEFICIAL_OWNERSHIP_BROKER_WRITES = 0
BENEFICIAL_OWNERSHIP_ORDER_WRITES = 0
BENEFICIAL_OWNERSHIP_PAPER_SUBMITS = 0
BENEFICIAL_OWNERSHIP_LIVE_WRITES = 0
BENEFICIAL_OWNERSHIP_AUTOMATION_WRITES = 0
BENEFICIAL_OWNERSHIP_AUTOMATIC_BROKER_FAILOVER = False
BENEFICIAL_OWNERSHIP_PHASE33_AUTHORITY = False


def _policy_payload() -> dict[str, object]:
    return {
        "contract_version": BENEFICIAL_OWNERSHIP_SCIENTIFIC_CONTRACT,
        "entry_source_repair_contract": BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_CONTRACT,
        "entry_source_repair_fingerprint": BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_FINGERPRINT,
        "entry_source_repair_status": BENEFICIAL_OWNERSHIP_ENTRY_SOURCE_REPAIR_STATUS,
        "entry_quarter_indexes": BENEFICIAL_OWNERSHIP_ENTRY_QUARTER_INDEXES,
        "entry_submission_success": BENEFICIAL_OWNERSHIP_ENTRY_SUBMISSION_SUCCESS,
        "entry_unique_subject_ciks": BENEFICIAL_OWNERSHIP_ENTRY_UNIQUE_SUBJECT_CIKS,
        "entry_unambiguous_mappings": BENEFICIAL_OWNERSHIP_ENTRY_UNAMBIGUOUS_MAPPINGS,
        "mechanism": BENEFICIAL_OWNERSHIP_MECHANISM,
        "source_window": [BENEFICIAL_OWNERSHIP_SOURCE_START, BENEFICIAL_OWNERSHIP_SOURCE_CUTOFF],
        "performance_signal_start": BENEFICIAL_OWNERSHIP_PERFORMANCE_SIGNAL_START,
        "development_last_signal": BENEFICIAL_OWNERSHIP_DEVELOPMENT_LAST_SIGNAL,
        "outer_embargo_start": BENEFICIAL_OWNERSHIP_OUTER_EMBARGO_START,
        "outer_embargo_end": BENEFICIAL_OWNERSHIP_OUTER_EMBARGO_END,
        "protected_start": BENEFICIAL_OWNERSHIP_PROTECTED_START,
        "protected_last_signal": BENEFICIAL_OWNERSHIP_PROTECTED_LAST_SIGNAL,
        "protected_outcome_end": BENEFICIAL_OWNERSHIP_PROTECTED_OUTCOME_END,
        "eligible_forms": list(BENEFICIAL_OWNERSHIP_ELIGIBLE_FORMS),
        "amendments_performance_eligible": BENEFICIAL_OWNERSHIP_AMENDMENTS_PERFORMANCE_ELIGIBLE,
        "percent_rule": BENEFICIAL_OWNERSHIP_PERCENT_RULE,
        "percent_valid_range": BENEFICIAL_OWNERSHIP_PERCENT_VALID_RANGE,
        "percent_bins": list(BENEFICIAL_OWNERSHIP_PERCENT_BINS),
        "hypotheses": [asdict(spec) for spec in BENEFICIAL_OWNERSHIP_HYPOTHESES],
        "source_sampling": {
            "development_per_form_family": BENEFICIAL_OWNERSHIP_DEVELOPMENT_SAMPLE_PER_FORM_FAMILY,
            "protected_per_form_family": BENEFICIAL_OWNERSHIP_PROTECTED_SAMPLE_PER_FORM_FAMILY,
            "rule": BENEFICIAL_OWNERSHIP_SOURCE_SAMPLE_RULE,
            "market_outcome_independent": BENEFICIAL_OWNERSHIP_SOURCE_SAMPLE_MARKET_OUTCOME_INDEPENDENT,
        },
        "public_availability_rule": BENEFICIAL_OWNERSHIP_PUBLIC_AVAILABILITY_RULE,
        "identity_rule": BENEFICIAL_OWNERSHIP_INSTRUMENT_RULE,
        "entry_rule": BENEFICIAL_OWNERSHIP_ENTRY_RULE,
        "exit_rule": BENEFICIAL_OWNERSHIP_EXIT_RULE,
        "primary_horizon_sessions": BENEFICIAL_OWNERSHIP_PRIMARY_HORIZON_SESSIONS,
        "diagnostic_horizons_sessions": list(BENEFICIAL_OWNERSHIP_DIAGNOSTIC_HORIZONS_SESSIONS),
        "benchmark": BENEFICIAL_OWNERSHIP_BENCHMARK,
        "primary_return": BENEFICIAL_OWNERSHIP_PRIMARY_RETURN,
        "unhedged_return": BENEFICIAL_OWNERSHIP_UNHEDGED_RETURN,
        "primary_cost_bps": BENEFICIAL_OWNERSHIP_PRIMARY_COST_BPS,
        "stress_cost_bps": BENEFICIAL_OWNERSHIP_STRESS_COST_BPS,
        "development_selection_fraction": BENEFICIAL_OWNERSHIP_DEVELOPMENT_SELECTION_FRACTION,
        "internal_purge_sessions": BENEFICIAL_OWNERSHIP_INTERNAL_PURGE_SESSIONS,
        "selection_folds": BENEFICIAL_OWNERSHIP_SELECTION_FOLDS,
        "internal_validation_folds": BENEFICIAL_OWNERSHIP_INTERNAL_VALIDATION_FOLDS,
        "protected_folds": BENEFICIAL_OWNERSHIP_PROTECTED_FOLDS,
        "bootstrap_block_sessions": BENEFICIAL_OWNERSHIP_BOOTSTRAP_BLOCK_SESSIONS,
        "bootstrap_replicates": BENEFICIAL_OWNERSHIP_BOOTSTRAP_REPLICATES,
        "bootstrap_seed": BENEFICIAL_OWNERSHIP_BOOTSTRAP_SEED,
        "selection_confidence": BENEFICIAL_OWNERSHIP_SELECTION_CONFIDENCE,
        "internal_confidence": BENEFICIAL_OWNERSHIP_INTERNAL_CONFIDENCE,
        "protected_confidence": BENEFICIAL_OWNERSHIP_PROTECTED_CONFIDENCE,
        "selection_min_event_rows": BENEFICIAL_OWNERSHIP_SELECTION_MIN_EVENT_ROWS,
        "selection_min_signal_sessions": BENEFICIAL_OWNERSHIP_SELECTION_MIN_SIGNAL_SESSIONS,
        "selection_min_unique_instruments": BENEFICIAL_OWNERSHIP_SELECTION_MIN_UNIQUE_INSTRUMENTS,
        "selection_min_positive_folds": BENEFICIAL_OWNERSHIP_SELECTION_MIN_POSITIVE_FOLDS,
        "internal_min_event_rows": BENEFICIAL_OWNERSHIP_INTERNAL_MIN_EVENT_ROWS,
        "internal_min_signal_sessions": BENEFICIAL_OWNERSHIP_INTERNAL_MIN_SIGNAL_SESSIONS,
        "internal_min_unique_instruments": BENEFICIAL_OWNERSHIP_INTERNAL_MIN_UNIQUE_INSTRUMENTS,
        "internal_min_positive_folds": BENEFICIAL_OWNERSHIP_INTERNAL_MIN_POSITIVE_FOLDS,
        "protected_min_event_rows": BENEFICIAL_OWNERSHIP_PROTECTED_MIN_EVENT_ROWS,
        "protected_min_signal_sessions": BENEFICIAL_OWNERSHIP_PROTECTED_MIN_SIGNAL_SESSIONS,
        "protected_min_unique_instruments": BENEFICIAL_OWNERSHIP_PROTECTED_MIN_UNIQUE_INSTRUMENTS,
        "protected_min_positive_folds": BENEFICIAL_OWNERSHIP_PROTECTED_MIN_POSITIVE_FOLDS,
        "min_positive_year_fraction": BENEFICIAL_OWNERSHIP_MIN_POSITIVE_YEAR_FRACTION,
        "min_year_signal_sessions": BENEFICIAL_OWNERSHIP_MIN_YEAR_SIGNAL_SESSIONS,
        "max_single_session_row_fraction": BENEFICIAL_OWNERSHIP_MAX_SINGLE_SESSION_ROW_FRACTION,
        "max_single_instrument_row_fraction": BENEFICIAL_OWNERSHIP_MAX_SINGLE_INSTRUMENT_ROW_FRACTION,
        "multiple_testing_method": BENEFICIAL_OWNERSHIP_MULTIPLE_TESTING_METHOD,
        "multiple_testing_alpha": BENEFICIAL_OWNERSHIP_MULTIPLE_TESTING_ALPHA,
        "selection_winner_rule": BENEFICIAL_OWNERSHIP_SELECTION_WINNER_RULE,
        "max_selection_winners": BENEFICIAL_OWNERSHIP_MAX_SELECTION_WINNERS,
        "max_finalists": BENEFICIAL_OWNERSHIP_MAX_FINALISTS,
        "runner_up_substitution_allowed": BENEFICIAL_OWNERSHIP_RUNNER_UP_SUBSTITUTION_ALLOWED,
        "primary_mean_positive_required": BENEFICIAL_OWNERSHIP_PRIMARY_MEAN_POSITIVE_REQUIRED,
        "primary_lcb_positive_required": BENEFICIAL_OWNERSHIP_PRIMARY_LCB_POSITIVE_REQUIRED,
        "stress_mean_positive_required": BENEFICIAL_OWNERSHIP_STRESS_MEAN_POSITIVE_REQUIRED,
        "unhedged_primary_mean_positive_required": BENEFICIAL_OWNERSHIP_UNHEDGED_PRIMARY_MEAN_POSITIVE_REQUIRED,
        "regulatory_era_diagnostic": BENEFICIAL_OWNERSHIP_REGULATORY_ERA_DIAGNOSTIC,
        "deflated_performance_diagnostic_required": BENEFICIAL_OWNERSHIP_DEFLATED_PERFORMANCE_DIAGNOSTIC_REQUIRED,
        "protected_source_only_precheck_required": BENEFICIAL_OWNERSHIP_PROTECTED_SOURCE_ONLY_PRECHECK_REQUIRED,
        "protected_returns_before_finalist_allowed": BENEFICIAL_OWNERSHIP_PROTECTED_RETURNS_BEFORE_FINALIST_ALLOWED,
        "protected_predictors_before_finalist_allowed": BENEFICIAL_OWNERSHIP_PROTECTED_PREDICTORS_BEFORE_FINALIST_ALLOWED,
        "protected_holdout_consumed_after_any_nonempty_return_read": BENEFICIAL_OWNERSHIP_PROTECTED_HOLDOUT_CONSUMED_AFTER_ANY_NONEMPTY_RETURN_READ,
        "provider_writes": BENEFICIAL_OWNERSHIP_PROVIDER_WRITES,
        "broker_reads": BENEFICIAL_OWNERSHIP_BROKER_READS,
        "broker_writes": BENEFICIAL_OWNERSHIP_BROKER_WRITES,
        "order_writes": BENEFICIAL_OWNERSHIP_ORDER_WRITES,
        "paper_submits": BENEFICIAL_OWNERSHIP_PAPER_SUBMITS,
        "live_writes": BENEFICIAL_OWNERSHIP_LIVE_WRITES,
        "automation_writes": BENEFICIAL_OWNERSHIP_AUTOMATION_WRITES,
        "automatic_broker_failover": BENEFICIAL_OWNERSHIP_AUTOMATIC_BROKER_FAILOVER,
        "phase33_authority": BENEFICIAL_OWNERSHIP_PHASE33_AUTHORITY,
    }


def beneficial_ownership_scientific_fingerprint() -> str:
    encoded = json.dumps(_policy_payload(), sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def scientific_contract_snapshot() -> dict[str, object]:
    return {**_policy_payload(), "fingerprint": beneficial_ownership_scientific_fingerprint()}
