from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date, timedelta

from packages.backtesting.outcomes import DEFAULT_COST_GRID_BPS, STRATEGY_OUTCOME_CONTRACT_VERSION
from packages.backtesting.phase24_gate1_policy import (
    PHASE24_GATE1_BOOTSTRAP_BLOCK_SESSIONS,
    PHASE24_GATE1_BOOTSTRAP_REPLICATES,
    PHASE24_GATE1_BOOTSTRAP_SEED,
    PHASE24_GATE1_INTERNAL_MIN_POSITIVE_FOLDS,
    PHASE24_GATE1_INTERNAL_MIN_RAW_ROWS,
    PHASE24_GATE1_INTERNAL_MIN_SIGNAL_SESSIONS,
    PHASE24_GATE1_INTERNAL_VALIDATION_CONFIDENCE,
    PHASE24_GATE1_INTERNAL_VALIDATION_FOLDS,
    PHASE24_GATE1_MAX_SINGLE_SESSION_ROW_FRACTION,
    PHASE24_GATE1_MIN_POSITIVE_REGIME_FRACTION,
    PHASE24_GATE1_MIN_POSITIVE_YEAR_FRACTION,
    PHASE24_GATE1_MIN_REGIME_SIGNAL_SESSIONS,
    PHASE24_GATE1_MIN_YEAR_SIGNAL_SESSIONS,
    PHASE24_GATE1_MULTIPLE_TESTING_ALPHA,
    PHASE24_GATE1_PRIMARY_COST_BPS,
    PHASE24_GATE1_PROTECTED_CONFIDENCE,
    PHASE24_GATE1_PROTECTED_FOLDS,
    PHASE24_GATE1_PROTECTED_MIN_POSITIVE_FOLDS,
    PHASE24_GATE1_PROTECTED_MIN_RAW_ROWS,
    PHASE24_GATE1_PROTECTED_MIN_SIGNAL_SESSIONS,
    PHASE24_GATE1_PURGE_SESSIONS,
    PHASE24_GATE1_SELECTION_CONFIDENCE,
    PHASE24_GATE1_SELECTION_FOLDS,
    PHASE24_GATE1_SELECTION_FRACTION,
    PHASE24_GATE1_SELECTION_MIN_POSITIVE_FOLDS,
    PHASE24_GATE1_SELECTION_MIN_RAW_ROWS,
    PHASE24_GATE1_SELECTION_MIN_SIGNAL_SESSIONS,
    PHASE24_GATE1_STRESS_COST_BPS,
)
from packages.ml.walk_forward_policy import (
    ML_WALK_FORWARD_FINAL_HOLDOUT_END,
    ML_WALK_FORWARD_FINAL_HOLDOUT_START,
)

from .phase25_gate7_policy import phase25_gate7_policy_fingerprint
from .phase25_policy import (
    PHASE25_BROKER_READS,
    PHASE25_BROKER_WRITES,
    PHASE25_LIVE_WRITES,
    PHASE25_ORDER_WRITES,
    PHASE25_PAPER_SUBMITS,
    PHASE25_PHASE11_SUPPORT_WRITES,
    PHASE25_PROTECTED_STRATEGY_EVIDENCE_READS,
    PHASE25_ROUTE_REPLAY_ORIGIN,
)


PHASE25_GATE8_CONTRACT_VERSION = (
    "phase25-gate8-v1-development-only-production-path-incumbent-attribution"
)
PHASE25_GATE9_CONTRACT_VERSION = (
    "phase25-gate9-v1-preregistered-production-path-robustness-internal-no-protected"
)
PHASE25_GATE10_CONTRACT_VERSION = (
    "phase25-gate10-v1-frozen-finalist-protected-confirmation-nonfresh-no-support-write"
)
PHASE25_GATE11_CONTRACT_VERSION = (
    "phase25-gate11-v1-cumulative-route-fidelity-closeout-no-support-write"
)
ACCEPTED_GATE7_POLICY_FINGERPRINT = (
    "2800bd82670b8f763a9c5f5c080301e20ab6462f82dd949f7cec0a800e989c31"
)

PHASE25_GATE8_DEVELOPMENT_START = PHASE25_ROUTE_REPLAY_ORIGIN
PHASE25_GATE8_PROTECTED_START = date.fromisoformat(ML_WALK_FORWARD_FINAL_HOLDOUT_START)
PHASE25_GATE8_PROTECTED_END = date.fromisoformat(ML_WALK_FORWARD_FINAL_HOLDOUT_END)
PHASE25_GATE8_DEVELOPMENT_END = PHASE25_GATE8_PROTECTED_START - timedelta(days=1)
PHASE25_GATE8_COST_GRID_BPS = DEFAULT_COST_GRID_BPS
PHASE25_GATE8_OUTCOME_CONTRACT_VERSION = STRATEGY_OUTCOME_CONTRACT_VERSION

PHASE25_GATE8_PROVIDER_READS = 0
PHASE25_GATE8_PROVIDER_WRITES = 0
PHASE25_GATE8_STRATEGY_RULE_EVALUATION_ALLOWED = True
PHASE25_GATE8_STRATEGY_RETURNS_READ_ALLOWED = True
PHASE25_GATE8_BROAD_COMPARATOR_ALLOWED = True
PHASE25_GATE8_PROTECTED_EVIDENCE_ALLOWED = False
PHASE25_GATE8_SUPPORT_REPLACEMENT_ALLOWED = False
PHASE25_GATE8_STRATEGY_RULE_CHANGES_ALLOWED = False
PHASE25_GATE8_OUTCOME_CHANGES_ALLOWED = False

# Gate9 deliberately reuses the already accepted Phase24 robustness machinery.
# The only strengthening is global Holm-Bonferroni across the eight fixed incumbents,
# rather than within challenger family/direction groups.
PHASE25_GATE9_SELECTION_FRACTION = PHASE24_GATE1_SELECTION_FRACTION
PHASE25_GATE9_PURGE_SESSIONS = PHASE24_GATE1_PURGE_SESSIONS
PHASE25_GATE9_SELECTION_FOLDS = PHASE24_GATE1_SELECTION_FOLDS
PHASE25_GATE9_INTERNAL_FOLDS = PHASE24_GATE1_INTERNAL_VALIDATION_FOLDS
PHASE25_GATE9_SELECTION_CONFIDENCE = PHASE24_GATE1_SELECTION_CONFIDENCE
PHASE25_GATE9_INTERNAL_CONFIDENCE = PHASE24_GATE1_INTERNAL_VALIDATION_CONFIDENCE
PHASE25_GATE9_PRIMARY_COST_BPS = PHASE24_GATE1_PRIMARY_COST_BPS
PHASE25_GATE9_STRESS_COST_BPS = PHASE24_GATE1_STRESS_COST_BPS
PHASE25_GATE9_SELECTION_MIN_RAW_ROWS = PHASE24_GATE1_SELECTION_MIN_RAW_ROWS
PHASE25_GATE9_SELECTION_MIN_SIGNAL_SESSIONS = PHASE24_GATE1_SELECTION_MIN_SIGNAL_SESSIONS
PHASE25_GATE9_SELECTION_MIN_POSITIVE_FOLDS = PHASE24_GATE1_SELECTION_MIN_POSITIVE_FOLDS
PHASE25_GATE9_INTERNAL_MIN_RAW_ROWS = PHASE24_GATE1_INTERNAL_MIN_RAW_ROWS
PHASE25_GATE9_INTERNAL_MIN_SIGNAL_SESSIONS = PHASE24_GATE1_INTERNAL_MIN_SIGNAL_SESSIONS
PHASE25_GATE9_INTERNAL_MIN_POSITIVE_FOLDS = PHASE24_GATE1_INTERNAL_MIN_POSITIVE_FOLDS
PHASE25_GATE9_MIN_POSITIVE_YEAR_FRACTION = PHASE24_GATE1_MIN_POSITIVE_YEAR_FRACTION
PHASE25_GATE9_MIN_YEAR_SIGNAL_SESSIONS = PHASE24_GATE1_MIN_YEAR_SIGNAL_SESSIONS
PHASE25_GATE9_MIN_POSITIVE_REGIME_FRACTION = PHASE24_GATE1_MIN_POSITIVE_REGIME_FRACTION
PHASE25_GATE9_MIN_REGIME_SIGNAL_SESSIONS = PHASE24_GATE1_MIN_REGIME_SIGNAL_SESSIONS
PHASE25_GATE9_MAX_SINGLE_SESSION_ROW_FRACTION = PHASE24_GATE1_MAX_SINGLE_SESSION_ROW_FRACTION
PHASE25_GATE9_BOOTSTRAP_BLOCK_SESSIONS = PHASE24_GATE1_BOOTSTRAP_BLOCK_SESSIONS
PHASE25_GATE9_BOOTSTRAP_REPLICATES = PHASE24_GATE1_BOOTSTRAP_REPLICATES
PHASE25_GATE9_BOOTSTRAP_SEED = PHASE24_GATE1_BOOTSTRAP_SEED
PHASE25_GATE9_MULTIPLE_TESTING_METHOD = "HOLM_BONFERRONI_GLOBAL_8_INCUMBENTS"
PHASE25_GATE9_MULTIPLE_TESTING_ALPHA = PHASE24_GATE1_MULTIPLE_TESTING_ALPHA
PHASE25_GATE9_PROTECTED_EVIDENCE_ALLOWED = False
PHASE25_GATE9_SUPPORT_REPLACEMENT_ALLOWED = False
PHASE25_GATE9_FALLBACK_AFTER_INTERNAL_FAILURE = False

PHASE25_GATE10_PROTECTED_START = PHASE25_GATE8_PROTECTED_START
PHASE25_GATE10_PROTECTED_END = PHASE25_GATE8_PROTECTED_END
PHASE25_GATE10_FOLDS = PHASE24_GATE1_PROTECTED_FOLDS
PHASE25_GATE10_CONFIDENCE = PHASE24_GATE1_PROTECTED_CONFIDENCE
PHASE25_GATE10_MIN_RAW_ROWS = PHASE24_GATE1_PROTECTED_MIN_RAW_ROWS
PHASE25_GATE10_MIN_SIGNAL_SESSIONS = PHASE24_GATE1_PROTECTED_MIN_SIGNAL_SESSIONS
PHASE25_GATE10_MIN_POSITIVE_FOLDS = PHASE24_GATE1_PROTECTED_MIN_POSITIVE_FOLDS
PHASE25_GATE10_PROTECTED_EVIDENCE_ALLOWED = True
PHASE25_GATE10_PROTECTED_EVIDENCE_FRESH = False
PHASE25_GATE10_FINALISTS_ONLY = True
PHASE25_GATE10_ZERO_FINALISTS_ZERO_PROTECTED_READS = True
PHASE25_GATE10_SUPPORT_REPLACEMENT_ALLOWED = False

PHASE25_GATE11_SUPPORT_REPLACEMENT_ALLOWED = False
PHASE25_GATE11_FUTURE_PROSPECTIVE_REQUIRED_FOR_AUTHORITY = True


@dataclass(frozen=True, slots=True)
class Phase25Gate8Policy:
    contract_version: str = PHASE25_GATE8_CONTRACT_VERSION
    gate7_policy_fingerprint: str = ACCEPTED_GATE7_POLICY_FINGERPRINT
    development_start: str = PHASE25_GATE8_DEVELOPMENT_START.isoformat()
    development_end: str = PHASE25_GATE8_DEVELOPMENT_END.isoformat()
    protected_start: str = PHASE25_GATE8_PROTECTED_START.isoformat()
    protected_end: str = PHASE25_GATE8_PROTECTED_END.isoformat()
    cost_grid_bps: tuple[float, ...] = PHASE25_GATE8_COST_GRID_BPS
    outcome_contract_version: str = PHASE25_GATE8_OUTCOME_CONTRACT_VERSION
    provider_reads: int = PHASE25_GATE8_PROVIDER_READS
    provider_writes: int = PHASE25_GATE8_PROVIDER_WRITES
    strategy_rule_evaluation_allowed: bool = PHASE25_GATE8_STRATEGY_RULE_EVALUATION_ALLOWED
    strategy_returns_read_allowed: bool = PHASE25_GATE8_STRATEGY_RETURNS_READ_ALLOWED
    broad_comparator_allowed: bool = PHASE25_GATE8_BROAD_COMPARATOR_ALLOWED
    protected_evidence_allowed: bool = PHASE25_GATE8_PROTECTED_EVIDENCE_ALLOWED
    support_replacement_allowed: bool = PHASE25_GATE8_SUPPORT_REPLACEMENT_ALLOWED
    strategy_rule_changes_allowed: bool = PHASE25_GATE8_STRATEGY_RULE_CHANGES_ALLOWED
    outcome_changes_allowed: bool = PHASE25_GATE8_OUTCOME_CHANGES_ALLOWED
    broker_reads: int = PHASE25_BROKER_READS
    broker_writes: int = PHASE25_BROKER_WRITES
    order_writes: int = PHASE25_ORDER_WRITES
    paper_submits: int = PHASE25_PAPER_SUBMITS
    live_writes: int = PHASE25_LIVE_WRITES
    phase11_support_writes: int = PHASE25_PHASE11_SUPPORT_WRITES
    protected_strategy_evidence_reads: int = PHASE25_PROTECTED_STRATEGY_EVIDENCE_READS

    def public_dict(self) -> dict[str, object]:
        payload = asdict(self)
        payload["cost_grid_bps"] = list(self.cost_grid_bps)
        return payload


PHASE25_GATE8_POLICY = Phase25Gate8Policy()


def _fingerprint(payload: dict[str, object]) -> str:
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def phase25_gate8_policy_fingerprint() -> str:
    return _fingerprint(PHASE25_GATE8_POLICY.public_dict())


@dataclass(frozen=True, slots=True)
class Phase25Gate9Policy:
    contract_version: str = PHASE25_GATE9_CONTRACT_VERSION
    gate8_policy_fingerprint: str = phase25_gate8_policy_fingerprint()
    selection_fraction: float = PHASE25_GATE9_SELECTION_FRACTION
    purge_sessions: int = PHASE25_GATE9_PURGE_SESSIONS
    selection_folds: int = PHASE25_GATE9_SELECTION_FOLDS
    internal_folds: int = PHASE25_GATE9_INTERNAL_FOLDS
    selection_confidence: float = PHASE25_GATE9_SELECTION_CONFIDENCE
    internal_confidence: float = PHASE25_GATE9_INTERNAL_CONFIDENCE
    primary_cost_bps: float = PHASE25_GATE9_PRIMARY_COST_BPS
    stress_cost_bps: float = PHASE25_GATE9_STRESS_COST_BPS
    multiple_testing_method: str = PHASE25_GATE9_MULTIPLE_TESTING_METHOD
    multiple_testing_alpha: float = PHASE25_GATE9_MULTIPLE_TESTING_ALPHA
    protected_evidence_allowed: bool = PHASE25_GATE9_PROTECTED_EVIDENCE_ALLOWED
    support_replacement_allowed: bool = PHASE25_GATE9_SUPPORT_REPLACEMENT_ALLOWED
    fallback_after_internal_failure: bool = PHASE25_GATE9_FALLBACK_AFTER_INTERNAL_FAILURE

    def public_dict(self) -> dict[str, object]:
        return asdict(self)


PHASE25_GATE9_POLICY = Phase25Gate9Policy()


def phase25_gate9_policy_fingerprint() -> str:
    return _fingerprint(PHASE25_GATE9_POLICY.public_dict())


@dataclass(frozen=True, slots=True)
class Phase25Gate10Policy:
    contract_version: str = PHASE25_GATE10_CONTRACT_VERSION
    gate9_policy_fingerprint: str = phase25_gate9_policy_fingerprint()
    protected_start: str = PHASE25_GATE10_PROTECTED_START.isoformat()
    protected_end: str = PHASE25_GATE10_PROTECTED_END.isoformat()
    folds: int = PHASE25_GATE10_FOLDS
    confidence: float = PHASE25_GATE10_CONFIDENCE
    min_raw_rows: int = PHASE25_GATE10_MIN_RAW_ROWS
    min_signal_sessions: int = PHASE25_GATE10_MIN_SIGNAL_SESSIONS
    min_positive_folds: int = PHASE25_GATE10_MIN_POSITIVE_FOLDS
    protected_evidence_allowed: bool = PHASE25_GATE10_PROTECTED_EVIDENCE_ALLOWED
    protected_evidence_fresh: bool = PHASE25_GATE10_PROTECTED_EVIDENCE_FRESH
    finalists_only: bool = PHASE25_GATE10_FINALISTS_ONLY
    zero_finalists_zero_protected_reads: bool = PHASE25_GATE10_ZERO_FINALISTS_ZERO_PROTECTED_READS
    support_replacement_allowed: bool = PHASE25_GATE10_SUPPORT_REPLACEMENT_ALLOWED

    def public_dict(self) -> dict[str, object]:
        return asdict(self)


PHASE25_GATE10_POLICY = Phase25Gate10Policy()


def phase25_gate10_policy_fingerprint() -> str:
    return _fingerprint(PHASE25_GATE10_POLICY.public_dict())


@dataclass(frozen=True, slots=True)
class Phase25Gate11Policy:
    contract_version: str = PHASE25_GATE11_CONTRACT_VERSION
    gate10_policy_fingerprint: str = phase25_gate10_policy_fingerprint()
    support_replacement_allowed: bool = PHASE25_GATE11_SUPPORT_REPLACEMENT_ALLOWED
    future_prospective_required_for_authority: bool = PHASE25_GATE11_FUTURE_PROSPECTIVE_REQUIRED_FOR_AUTHORITY

    def public_dict(self) -> dict[str, object]:
        return asdict(self)


PHASE25_GATE11_POLICY = Phase25Gate11Policy()


def phase25_gate11_policy_fingerprint() -> str:
    return _fingerprint(PHASE25_GATE11_POLICY.public_dict())


assert phase25_gate7_policy_fingerprint() == ACCEPTED_GATE7_POLICY_FINGERPRINT
assert PHASE25_GATE8_DEVELOPMENT_START == date(2021, 8, 16)
assert PHASE25_GATE8_DEVELOPMENT_END < PHASE25_GATE8_PROTECTED_START <= PHASE25_GATE8_PROTECTED_END
assert PHASE25_GATE8_COST_GRID_BPS == (0.0, 5.0, 10.0, 25.0)
assert PHASE25_GATE8_OUTCOME_CONTRACT_VERSION == "strategy-outcome-v1-direction-adjusted-three-session-return"
assert PHASE25_GATE8_PROVIDER_READS == PHASE25_GATE8_PROVIDER_WRITES == 0
assert PHASE25_GATE8_STRATEGY_RULE_EVALUATION_ALLOWED is True
assert PHASE25_GATE8_STRATEGY_RETURNS_READ_ALLOWED is True
assert PHASE25_GATE8_BROAD_COMPARATOR_ALLOWED is True
assert PHASE25_GATE8_PROTECTED_EVIDENCE_ALLOWED is False
assert PHASE25_GATE8_SUPPORT_REPLACEMENT_ALLOWED is False
assert PHASE25_GATE8_STRATEGY_RULE_CHANGES_ALLOWED is False
assert PHASE25_GATE8_OUTCOME_CHANGES_ALLOWED is False
assert PHASE25_GATE9_MULTIPLE_TESTING_METHOD == "HOLM_BONFERRONI_GLOBAL_8_INCUMBENTS"
assert PHASE25_GATE9_PROTECTED_EVIDENCE_ALLOWED is False
assert PHASE25_GATE9_SUPPORT_REPLACEMENT_ALLOWED is False
assert PHASE25_GATE10_PROTECTED_EVIDENCE_ALLOWED is True
assert PHASE25_GATE10_PROTECTED_EVIDENCE_FRESH is False
assert PHASE25_GATE10_FINALISTS_ONLY is True
assert PHASE25_GATE10_ZERO_FINALISTS_ZERO_PROTECTED_READS is True
assert PHASE25_GATE10_SUPPORT_REPLACEMENT_ALLOWED is False
assert PHASE25_GATE11_SUPPORT_REPLACEMENT_ALLOWED is False
assert PHASE25_GATE11_FUTURE_PROSPECTIVE_REQUIRED_FOR_AUTHORITY is True
assert PHASE25_BROKER_READS == PHASE25_BROKER_WRITES == 0
assert PHASE25_ORDER_WRITES == PHASE25_PAPER_SUBMITS == PHASE25_LIVE_WRITES == 0
assert PHASE25_PHASE11_SUPPORT_WRITES == 0
assert PHASE25_PROTECTED_STRATEGY_EVIDENCE_READS == 0
