from __future__ import annotations


ML_BASELINE_POLICY_CONTRACT_VERSION = (
    "ml-baseline-policy-v1-prior-floor-linear-discrimination-reference"
)
ML_BASELINE_POLICY_ACCEPTED = True
ML_BASELINE_BENCHMARK_TARGET_DATE = "2026-08-14"
ML_BASELINE_ACCEPTED_OOS_ROWS = 3_978_577
ML_BASELINE_ACCEPTED_FOLDS = 10
ML_BASELINE_FINAL_HOLDOUT_ACCESSED = False

ML_BASELINE_PRIOR_WEIGHTED_LOG_LOSS = 0.979113
ML_BASELINE_PRIOR_WEIGHTED_BRIER = 0.581075
ML_BASELINE_PRIOR_WEIGHTED_ACCURACY = 0.572165
ML_BASELINE_PRIOR_WEIGHTED_MACRO_AUC = 0.500000
ML_BASELINE_PRIOR_WEIGHTED_ECE = 0.018040

ML_BASELINE_LINEAR_WEIGHTED_LOG_LOSS = 1.019090
ML_BASELINE_LINEAR_WEIGHTED_BRIER = 0.592818
ML_BASELINE_LINEAR_WEIGHTED_ACCURACY = 0.569650
ML_BASELINE_LINEAR_WEIGHTED_MACRO_AUC = 0.545420
ML_BASELINE_LINEAR_WEIGHTED_ECE = 0.062187

ML_BASELINE_LINEAR_RELATIVE_LOG_LOSS_IMPROVEMENT = -0.04083
ML_BASELINE_LINEAR_RELATIVE_BRIER_IMPROVEMENT = -0.02021
ML_BASELINE_LINEAR_LOG_LOSS_FOLD_WINS = 0
ML_BASELINE_LINEAR_BRIER_FOLD_WINS = 2

# Gate 8 accepts the benchmark evidence, not the SGD model as production-ready.
# The class-prior baseline remains the probability-quality floor. The learned
# linear model is retained as a discrimination reference because it produced
# macro OVR AUC > 0.5 across the accepted OOS period, while its materially worse
# log loss/Brier/ECE demonstrates that raw linear probabilities are not suitable
# for promotion. Calibration remains explicitly deferred to Gate 10.
ML_BASELINE_PRIOR_ROLE = "PROBABILITY_QUALITY_FLOOR"
ML_BASELINE_LINEAR_ROLE = "LEARNED_LINEAR_DISCRIMINATION_REFERENCE"
ML_BASELINE_LINEAR_PRODUCTION_READY = False
ML_BASELINE_CALIBRATION_DEFERRED_TO_GATE10 = True
ML_GATE9_CANDIDATE_MODEL_BENCHMARK_CURRENT = True
