from __future__ import annotations


ML_CALIBRATION_POLICY_CONTRACT_VERSION = (
    "ml-calibration-policy-v1-raw-no-posthoc-calibration"
)
ML_CALIBRATION_POLICY_ACCEPTED = True
ML_CALIBRATION_ACCEPTED_METHOD = "raw"
ML_CALIBRATION_POSTHOC_ENABLED = False
ML_CALIBRATION_ACCEPTED_MODEL = "hgb_leaf15_iter100"
ML_CALIBRATION_ACCEPTED_FOLDS = 10
ML_CALIBRATION_ACCEPTED_OOS_ROWS = 3_978_577
ML_CALIBRATION_FINAL_HOLDOUT_ACCESSED = False

ML_CALIBRATION_RAW_LOG_LOSS = 0.967042
ML_CALIBRATION_RAW_BRIER = 0.572424
ML_CALIBRATION_RAW_ACCURACY = 0.573086
ML_CALIBRATION_RAW_MACRO_AUC = 0.565518
ML_CALIBRATION_RAW_ECE = 0.022187

ML_CALIBRATION_PLATT_LOG_LOSS = 0.970672
ML_CALIBRATION_PLATT_BRIER = 0.574249
ML_CALIBRATION_PLATT_ACCURACY = 0.573158
ML_CALIBRATION_PLATT_MACRO_AUC = 0.566292
ML_CALIBRATION_PLATT_ECE = 0.031047
ML_CALIBRATION_PLATT_LOG_LOSS_FOLD_WINS = 4
ML_CALIBRATION_PLATT_BRIER_FOLD_WINS = 3

ML_CALIBRATION_ISOTONIC_LOG_LOSS = 0.970600
ML_CALIBRATION_ISOTONIC_BRIER = 0.574184
ML_CALIBRATION_ISOTONIC_ACCURACY = 0.573205
ML_CALIBRATION_ISOTONIC_MACRO_AUC = 0.566439
ML_CALIBRATION_ISOTONIC_ECE = 0.030268
ML_CALIBRATION_ISOTONIC_LOG_LOSS_FOLD_WINS = 5
ML_CALIBRATION_ISOTONIC_BRIER_FOLD_WINS = 5

# Gate 10 prioritizes probability quality over tiny discrimination gains. Both
# post-hoc candidates slightly increased macro AUC, but both worsened aggregate
# log loss, multiclass Brier, and ECE versus the already well-behaved raw HGB
# probabilities. Their fold-win evidence was also inconsistent. The production
# policy therefore preserves the raw candidate probabilities without a post-hoc
# calibration layer. This is an affirmative no-calibration decision, not a
# deferred calibration implementation.
ML_CALIBRATION_SELECTION_REASON = (
    "RAW_WINS_LOGLOSS_BRIER_ECE_AND_POSTHOC_FOLD_CONSISTENCY_IS_INSUFFICIENT"
)
ML_GATE11_ROBUSTNESS_CURRENT = True
