from __future__ import annotations


ML_CANDIDATE_MODEL_POLICY_CONTRACT_VERSION = (
    "ml-candidate-model-policy-v1-hgb-leaf15-probability-quality-winner"
)
ML_CANDIDATE_MODEL_POLICY_ACCEPTED = True
ML_CANDIDATE_MODEL_ACCEPTED_MODEL = "hgb_leaf15_iter100"
ML_CANDIDATE_MODEL_ACCEPTED_TRAIN_CAP_ROWS = 1_000_000
ML_CANDIDATE_MODEL_ACCEPTED_FOLDS = 10
ML_CANDIDATE_MODEL_ACCEPTED_OOS_ROWS = 3_978_577
ML_CANDIDATE_MODEL_FINAL_HOLDOUT_ACCESSED = False

ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS = 0.967042
ML_CANDIDATE_MODEL_ACCEPTED_BRIER = 0.572424
ML_CANDIDATE_MODEL_ACCEPTED_ACCURACY = 0.573086
ML_CANDIDATE_MODEL_ACCEPTED_MACRO_AUC = 0.565518
ML_CANDIDATE_MODEL_ACCEPTED_ECE = 0.022187
ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS_IMPROVEMENT_VS_PRIOR = 0.01233
ML_CANDIDATE_MODEL_ACCEPTED_BRIER_IMPROVEMENT_VS_PRIOR = 0.01489
ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS_FOLD_WINS_VS_PRIOR = 10
ML_CANDIDATE_MODEL_ACCEPTED_BRIER_FOLD_WINS_VS_PRIOR = 10

ML_CANDIDATE_MODEL_CHALLENGER_MODEL = "hgb_leaf31_iter100"
ML_CANDIDATE_MODEL_CHALLENGER_LOG_LOSS = 0.967220
ML_CANDIDATE_MODEL_CHALLENGER_BRIER = 0.572494
ML_CANDIDATE_MODEL_CHALLENGER_ACCURACY = 0.572603
ML_CANDIDATE_MODEL_CHALLENGER_MACRO_AUC = 0.566103
ML_CANDIDATE_MODEL_CHALLENGER_ECE = 0.023019

# Gate 9 promotes the lower-capacity candidate because probability quality is the
# primary objective for Phase 10. The 31-leaf challenger gains only ~0.0006 macro
# AUC while losing on aggregate log loss, Brier, ECE, accuracy, runtime/complexity,
# and log-loss fold consistency. Calibration remains a separate Gate 10 decision.
ML_CANDIDATE_MODEL_PRODUCTION_RAW_PROBABILITY_READY = True
ML_GATE10_CALIBRATION_CURRENT = True
