from __future__ import annotations

from pathlib import Path
from typing import Any

import duckdb
import numpy as np

from packages.core.atomic_io import atomic_write_text
from packages.features.engine import compute_core_features
from packages.features.feature_registry import CORE_FEATURE_REGISTRY
from packages.features.historical_backfill_replay_build import _sql_path_list, _sql_string
from packages.features.historical_backfill_replay_validation import (
    HistoricalBackfillDailyFeatureReplayValidator,
)
from packages.features.verification import market_key_series_equal


GATE9_DAILY_REPLAY_VALIDATION_V2_CONTRACT_VERSION = (
    "historical-backfill-feature-replay-validation-v2-independent-candidate-float64-tolerance"
)
GATE9_SENTINEL_STRICT_ATOL = 1e-12
GATE9_SENTINEL_STRICT_RTOL = 1e-12
GATE9_SENTINEL_ACCEPTANCE_ATOL = 1e-8
GATE9_SENTINEL_ACCEPTANCE_RTOL = 1e-12


def feature_numeric_equivalence_diagnostics(
    expected_values: np.ndarray,
    actual_values: np.ndarray,
    feature_names: list[str],
) -> dict[str, object]:
    """Compare mathematically equivalent float64 feature paths with a locked tolerance.

    Batch verification uses pandas rolling kernels while persisted ATLAS history is
    generated by the live-compatible incremental engine. Those paths can differ by
    a few float64 rounding units even when formulas and state are identical. NaN
    placement remains exact, infinities are forbidden, and the acceptance tolerance
    is deliberately much tighter than any economically meaningful feature change.
    """

    expected = np.asarray(expected_values, dtype="float64")
    actual = np.asarray(actual_values, dtype="float64")
    if expected.shape != actual.shape:
        raise ValueError(
            f"feature equivalence shape mismatch: expected={expected.shape} actual={actual.shape}"
        )
    if expected.ndim != 2 or expected.shape[1] != len(feature_names):
        raise ValueError("feature equivalence columns do not match feature_names")

    expected_nan = np.isnan(expected)
    actual_nan = np.isnan(actual)
    nan_mask_mismatches = int(np.count_nonzero(expected_nan != actual_nan))
    expected_infinite = int(np.count_nonzero(np.isinf(expected)))
    actual_infinite = int(np.count_nonzero(np.isinf(actual)))

    strict_close = np.isclose(
        expected,
        actual,
        rtol=GATE9_SENTINEL_STRICT_RTOL,
        atol=GATE9_SENTINEL_STRICT_ATOL,
        equal_nan=True,
    )
    acceptance_close = np.isclose(
        expected,
        actual,
        rtol=GATE9_SENTINEL_ACCEPTANCE_RTOL,
        atol=GATE9_SENTINEL_ACCEPTANCE_ATOL,
        equal_nan=True,
    )

    finite = np.isfinite(expected) & np.isfinite(actual)
    absolute_error = np.full(expected.shape, np.nan, dtype="float64")
    absolute_error[finite] = np.abs(expected[finite] - actual[finite])
    max_abs_error = (
        float(np.nanmax(absolute_error)) if np.any(finite) else 0.0
    )

    relative_error = np.full(expected.shape, np.nan, dtype="float64")
    relative_denominator = np.abs(expected)
    relative_mask = finite & (relative_denominator > 1e-12)
    relative_error[relative_mask] = (
        absolute_error[relative_mask] / relative_denominator[relative_mask]
    )
    max_relative_error = (
        float(np.nanmax(relative_error)) if np.any(relative_mask) else 0.0
    )

    per_feature: list[dict[str, object]] = []
    for index, feature_name in enumerate(feature_names):
        feature_finite = finite[:, index]
        feature_abs = absolute_error[:, index]
        feature_rel = relative_error[:, index]
        feature_record = {
            "feature": feature_name,
            "strict_mismatches": int(np.count_nonzero(~strict_close[:, index])),
            "acceptance_mismatches": int(np.count_nonzero(~acceptance_close[:, index])),
            "nan_mask_mismatches": int(
                np.count_nonzero(expected_nan[:, index] != actual_nan[:, index])
            ),
            "max_abs_error": (
                float(np.nanmax(feature_abs)) if np.any(feature_finite) else 0.0
            ),
            "max_relative_error": (
                float(np.nanmax(feature_rel))
                if np.any(np.isfinite(feature_rel))
                else 0.0
            ),
        }
        per_feature.append(feature_record)

    return {
        "strict_mismatches": int(np.count_nonzero(~strict_close)),
        "acceptance_mismatches": int(np.count_nonzero(~acceptance_close)),
        "nan_mask_mismatches": nan_mask_mismatches,
        "expected_infinite_values": expected_infinite,
        "actual_infinite_values": actual_infinite,
        "max_abs_error": max_abs_error,
        "max_relative_error": max_relative_error,
        "strict_atol": GATE9_SENTINEL_STRICT_ATOL,
        "strict_rtol": GATE9_SENTINEL_STRICT_RTOL,
        "acceptance_atol": GATE9_SENTINEL_ACCEPTANCE_ATOL,
        "acceptance_rtol": GATE9_SENTINEL_ACCEPTANCE_RTOL,
        "per_feature": per_feature,
    }


class HistoricalBackfillDailyFeatureReplayValidatorV2(
    HistoricalBackfillDailyFeatureReplayValidator
):
    """Gate 9-B validator with explicit float64 path-equivalence semantics."""

    def _sentinel_feature_equivalence(
        self,
        candidate_paths: list[Path],
        canonical_paths: list[Path],
    ) -> dict[str, object]:
        sentinels = (
            "SPY",
            "QQQ",
            "IWM",
            "DIA",
            "AAPL",
            "MSFT",
            "AMZN",
            "GOOG",
            "GOOGL",
            "IBM",
            "XOM",
            "JPM",
        )
        in_list = ",".join(_sql_string(symbol) for symbol in sentinels)
        feature_names = [definition.name for definition in CORE_FEATURE_REGISTRY.all()]
        feature_projection = ", ".join(f'"{name}"' for name in feature_names)
        con = duckdb.connect(":memory:")
        try:
            source = con.execute(
                f"""
                SELECT symbol, timestamp_utc, high, low, close, volume
                FROM read_parquet({_sql_path_list(canonical_paths)}, hive_partitioning=false)
                WHERE symbol IN ({in_list})
                ORDER BY symbol, timestamp_utc
                """
            ).fetch_df()
            actual = con.execute(
                f"""
                SELECT symbol, timestamp_utc, {feature_projection}
                FROM read_parquet({_sql_path_list(candidate_paths)}, hive_partitioning=false)
                WHERE symbol IN ({in_list})
                ORDER BY symbol, timestamp_utc
                """
            ).fetch_df()
        finally:
            con.close()

        expected = compute_core_features(source)
        expected = expected[["symbol", "timestamp_utc", *feature_names]].reset_index(drop=True)
        actual = actual[["symbol", "timestamp_utc", *feature_names]].reset_index(drop=True)
        keys_exact = (
            len(expected) == len(actual)
            and market_key_series_equal(expected["symbol"], actual["symbol"], "symbol")
            and market_key_series_equal(
                expected["timestamp_utc"], actual["timestamp_utc"], "timestamp_utc"
            )
        )
        if not keys_exact:
            return {
                "sentinels": len(sentinels),
                "rows": int(len(actual)),
                "keys_exact": False,
                "feature_mismatches": -1,
                "strict_feature_mismatches": -1,
                "nan_mask_mismatches": -1,
                "expected_infinite_values": -1,
                "actual_infinite_values": -1,
                "max_abs_error": None,
                "max_relative_error": None,
                "acceptance_atol": GATE9_SENTINEL_ACCEPTANCE_ATOL,
                "acceptance_rtol": GATE9_SENTINEL_ACCEPTANCE_RTOL,
                "per_feature": [],
            }

        expected_values = expected[feature_names].to_numpy(dtype="float64", na_value=np.nan)
        actual_values = actual[feature_names].to_numpy(dtype="float64", na_value=np.nan)
        diagnostics = feature_numeric_equivalence_diagnostics(
            expected_values,
            actual_values,
            feature_names,
        )
        return {
            "sentinels": len(sentinels),
            "rows": int(len(actual)),
            "keys_exact": True,
            "feature_mismatches": int(diagnostics["acceptance_mismatches"]),
            "strict_feature_mismatches": int(diagnostics["strict_mismatches"]),
            "nan_mask_mismatches": int(diagnostics["nan_mask_mismatches"]),
            "expected_infinite_values": int(diagnostics["expected_infinite_values"]),
            "actual_infinite_values": int(diagnostics["actual_infinite_values"]),
            "max_abs_error": diagnostics["max_abs_error"],
            "max_relative_error": diagnostics["max_relative_error"],
            "strict_atol": diagnostics["strict_atol"],
            "strict_rtol": diagnostics["strict_rtol"],
            "acceptance_atol": diagnostics["acceptance_atol"],
            "acceptance_rtol": diagnostics["acceptance_rtol"],
            "per_feature": diagnostics["per_feature"],
        }

    def run(self) -> dict[str, object]:
        report = super().run()
        sentinel = dict(report["liquid_sentinel_proof"])
        checks = dict(report["checks"])
        checks["liquid_sentinel_features_exact"] = (
            sentinel.get("feature_mismatches") == 0
            and sentinel.get("nan_mask_mismatches") == 0
            and sentinel.get("expected_infinite_values") == 0
            and sentinel.get("actual_infinite_values") == 0
        )
        report["validation_contract_version"] = (
            GATE9_DAILY_REPLAY_VALIDATION_V2_CONTRACT_VERSION
        )
        report["checks"] = checks
        report["pass"] = all(checks.values())
        atomic_write_text(
            self.report_path,
            __import__("json").dumps(report, indent=2, sort_keys=True) + "\n",
        )
        return report
