from pathlib import Path

path = Path("docs/roadmap.md")
text = path.read_text(encoding="utf-8")

old = """**B35 retained-artifact robustness package is IMPLEMENTED / ACCEPTANCE ACTIVE in PR #78.** It validates the complete accepted analysis/receipt chain, creates aligned complete-session research profiles for the four B34 strategies and frozen selector, and computes the exact retained-artifact gates: cost robustness, deterministic 10,000-draw session-bootstrap downside/drawdown uncertainty, loss streaks, session contribution concentration, selected-cell/profile BH-FDR q=.05, Deflated Sharpe, and 16-partition CSCV/PBO. Cash is a same-unit benchmark. The accepted A34 account replay is contextual only because its daily strategy set, portfolio construction, date scope and costs are not statistically identical to B35. The frozen minute-path perturbations for entry delay, gap threshold, opening-range duration, premarket rel-volume threshold, and consolidation range cannot be reconstructed exactly from fired-opportunity compact artifacts and therefore fail closed as `REQUIRES_TARGETED_MINUTE_REPLAY`; no approximation is allowed. After accepted merge run `.\\.venv\\Scripts\\python.exe scripts\\run_b35_robustness_analysis.py`. This package opens no new minute outcomes, consumed master or future blind and grants no promotion/PAPER/LIVE/provider/broker authority.

Next Track-B sequence: (1) accept/merge PR #78 only after exact-head Windows+Ubuntu regression is green; (2) run the retained-artifact robustness command once; (3) review its BH-FDR, Deflated-Sharpe, PBO/CSCV, bootstrap-tail, loss-streak/concentration and cost results; (4) implement one exact targeted minute-path perturbation replay that evaluates the remaining preregistered perturbations together in one pass, without changing the canonical B35 v1 result; (5) record the final B35 research disposition without promotion; (6) freeze any justified condition-gated/calibrated successors plus the eight-new-family/confluence contract under new fingerprints; (7) later evaluate the genuinely new future blind only after required accrual and without refitting on it; and (8) never reuse the consumed master interval. Full mechanics and methodology anchors remain in `docs/b35_a36_preoutcome_conditional_evidence.md`."""
new = """**B35 retained-artifact robustness is COMPLETE / NO PROMOTION; exact targeted minute perturbations are CURRENT in PR #79.** PR #78 merged as `83d09c424a02883f7d3529a39c62294dcbaf6bc2`; workstation robustness fingerprint `c4489478e82a535ef890fd017e47c9594ad9d590d439c5f55089426bd8565107` covers 2,079 complete XNYS test sessions. All five declared 50-bps profiles have negative mean session return and Deflated-Sharpe probability `0.0`; 13 selected-cell hypotheses produced 0 BH-FDR q=.05 rejections. The frozen selector retains positive low-cost evidence at 0/10/25 bps but is negative at 50/100 bps. PBO/CSCV ~0.01% is ranking-stability context only, not a profitability claim. PR #79 implements the remaining frozen minute-path perturbations together in one DEVELOPMENT-only, restartable, hash-receipted pass with 27 one-axis-at-a-time strategy/variant profiles and per-group canonical baseline-equivalence gates. It does not refit the selector or rewrite B35 v1 and grants no promotion/PAPER/LIVE/provider/broker/master/future authority.

Next Track-B sequence: (1) accept/merge PR #79 only after exact-head Windows+Ubuntu regression is green; (2) run `.\\.venv\\Scripts\\python.exe scripts\\run_b35_targeted_perturbations.py --authorize-targeted-perturbations` once; (3) review the 27 diagnostic variant profiles and record the final B35 research disposition without promotion or v1 rewrite; (4) freeze only justified condition-gated/calibrated successor hypotheses plus the eight-new-family/confluence contract under new fingerprints; (5) implement and test the successor library on permitted evidence; (6) later evaluate the genuinely new future blind only after required accrual and without refitting on it; and (7) never reuse the consumed master interval. Full mechanics and methodology anchors remain in `docs/b35_a36_preoutcome_conditional_evidence.md`."""
assert old in text
text = text.replace(old, new, 1)

text = text.replace(
    "20. Every repository-changing implementation package updates both living documents\n    in the same commit before acceptance/merge.",
    "20. Every repository-changing implementation package updates README and roadmap before acceptance/merge; any package changing or interpreting strategy evidence also updates the Strategy Evidence Register in the same package.",
)
text = text.replace(
    "and updates to both\nliving documents in the same accepted package.",
    "and updates to all applicable\nliving documents in the same accepted package.",
)

path.write_text(text, encoding="utf-8")
