from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from packages.ml.final_acceptance_policy import (
    ML_FINAL_ACCEPTANCE_BRIER_IMPROVEMENT_VS_PRIOR,
    ML_FINAL_ACCEPTANCE_GATE12_ARTIFACTS_VERIFIED,
    ML_FINAL_ACCEPTANCE_HOLDOUT_END,
    ML_FINAL_ACCEPTANCE_HOLDOUT_ROWS,
    ML_FINAL_ACCEPTANCE_HOLDOUT_SESSIONS,
    ML_FINAL_ACCEPTANCE_HOLDOUT_START,
    ML_FINAL_ACCEPTANCE_LOG_LOSS_IMPROVEMENT_VS_PRIOR,
    ML_FINAL_ACCEPTANCE_MODEL_BRIER,
    ML_FINAL_ACCEPTANCE_MODEL_ID,
    ML_FINAL_ACCEPTANCE_MODEL_LOG_LOSS,
    ML_FINAL_ACCEPTANCE_MODEL_MACRO_AUC,
    ML_FINAL_ACCEPTANCE_MODEL_STATUS,
    ML_FINAL_ACCEPTANCE_POLICY_ACCEPTED,
    ML_FINAL_ACCEPTANCE_POLICY_CONTRACT_VERSION,
    ML_FINAL_ACCEPTANCE_PRIOR_BRIER,
    ML_FINAL_ACCEPTANCE_PRIOR_LOG_LOSS,
    ML_FINAL_ACCEPTANCE_PURGE_SESSIONS,
    ML_FINAL_ACCEPTANCE_REPLAY_MAX_ABS_PROBABILITY_DIFF,
    ML_FINAL_ACCEPTANCE_REPLAY_PASSED,
    ML_FINAL_ACCEPTANCE_TRAINING_ENDPOINTS_IN_HOLDOUT,
    ML_PHASE10_ACCEPTED,
)
from packages.ml.model_registry_policy import (
    ML_MODEL_REGISTRY_POLICY_ACCEPTED,
    ML_MODEL_REGISTRY_POLICY_CONTRACT_VERSION,
)


def main() -> int:
    assert ML_MODEL_REGISTRY_POLICY_ACCEPTED is True
    assert ML_FINAL_ACCEPTANCE_POLICY_ACCEPTED is True
    assert ML_PHASE10_ACCEPTED is True
    assert ML_FINAL_ACCEPTANCE_MODEL_STATUS == "ACCEPTED_PRODUCTION_MODEL"
    assert len(ML_FINAL_ACCEPTANCE_PURGE_SESSIONS) == 3
    assert ML_FINAL_ACCEPTANCE_TRAINING_ENDPOINTS_IN_HOLDOUT == 0
    assert ML_FINAL_ACCEPTANCE_HOLDOUT_SESSIONS == 63
    assert ML_FINAL_ACCEPTANCE_HOLDOUT_ROWS == 454_773
    assert ML_FINAL_ACCEPTANCE_MODEL_LOG_LOSS < ML_FINAL_ACCEPTANCE_PRIOR_LOG_LOSS
    assert ML_FINAL_ACCEPTANCE_MODEL_BRIER < ML_FINAL_ACCEPTANCE_PRIOR_BRIER
    assert ML_FINAL_ACCEPTANCE_MODEL_MACRO_AUC >= 0.52
    assert ML_FINAL_ACCEPTANCE_REPLAY_PASSED is True
    assert ML_FINAL_ACCEPTANCE_REPLAY_MAX_ABS_PROBABILITY_DIFF <= 1e-12
    assert ML_FINAL_ACCEPTANCE_GATE12_ARTIFACTS_VERIFIED == 10

    print(f"ML Gate 12 registry policy: {ML_MODEL_REGISTRY_POLICY_CONTRACT_VERSION}")
    print(f"ML Gate 13 acceptance policy: {ML_FINAL_ACCEPTANCE_POLICY_CONTRACT_VERSION}")
    print(f"ML accepted production model: {ML_FINAL_ACCEPTANCE_MODEL_ID}")
    print(
        "ML protected holdout: "
        f"{ML_FINAL_ACCEPTANCE_HOLDOUT_START}->{ML_FINAL_ACCEPTANCE_HOLDOUT_END} / "
        f"{ML_FINAL_ACCEPTANCE_HOLDOUT_SESSIONS} sessions / {ML_FINAL_ACCEPTANCE_HOLDOUT_ROWS:,} rows"
    )
    print(
        "ML final holdout evidence: "
        f"logloss={ML_FINAL_ACCEPTANCE_MODEL_LOG_LOSS:.6f} "
        f"brier={ML_FINAL_ACCEPTANCE_MODEL_BRIER:.6f} "
        f"auc={ML_FINAL_ACCEPTANCE_MODEL_MACRO_AUC:.6f}"
    )
    print(
        "ML final improvements vs prior: "
        f"logloss={ML_FINAL_ACCEPTANCE_LOG_LOSS_IMPROVEMENT_VS_PRIOR:.3%} / "
        f"brier={ML_FINAL_ACCEPTANCE_BRIER_IMPROVEMENT_VS_PRIOR:.3%}"
    )
    print(
        "ML final reproducibility/leakage: "
        f"replay_diff={ML_FINAL_ACCEPTANCE_REPLAY_MAX_ABS_PROBABILITY_DIFF:.3e} / "
        f"training_endpoints_in_holdout={ML_FINAL_ACCEPTANCE_TRAINING_ENDPOINTS_IN_HOLDOUT}"
    )
    print("Phase 10 ML Probability & Evaluation Layer: ACCEPTED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
