from __future__ import annotations

from packages.ml.baseline_policy import (
    ML_BASELINE_ACCEPTED_FOLDS,
    ML_BASELINE_ACCEPTED_OOS_ROWS,
    ML_BASELINE_CALIBRATION_DEFERRED_TO_GATE10,
    ML_BASELINE_FINAL_HOLDOUT_ACCESSED,
    ML_BASELINE_LINEAR_BRIER_FOLD_WINS,
    ML_BASELINE_LINEAR_LOG_LOSS_FOLD_WINS,
    ML_BASELINE_LINEAR_PRODUCTION_READY,
    ML_BASELINE_LINEAR_ROLE,
    ML_BASELINE_LINEAR_WEIGHTED_MACRO_AUC,
    ML_BASELINE_LINEAR_WEIGHTED_ECE,
    ML_BASELINE_LINEAR_WEIGHTED_LOG_LOSS,
    ML_BASELINE_POLICY_ACCEPTED,
    ML_BASELINE_POLICY_CONTRACT_VERSION,
    ML_BASELINE_PRIOR_ROLE,
    ML_BASELINE_PRIOR_WEIGHTED_ECE,
    ML_BASELINE_PRIOR_WEIGHTED_LOG_LOSS,
    ML_GATE9_CANDIDATE_MODEL_BENCHMARK_CURRENT,
)


def test_phase10_gate8_baseline_policy_is_accepted_without_promoting_linear_model() -> None:
    assert ML_BASELINE_POLICY_CONTRACT_VERSION == (
        "ml-baseline-policy-v1-prior-floor-linear-discrimination-reference"
    )
    assert ML_BASELINE_POLICY_ACCEPTED is True
    assert ML_BASELINE_ACCEPTED_FOLDS == 10
    assert ML_BASELINE_ACCEPTED_OOS_ROWS == 3_978_577
    assert ML_BASELINE_FINAL_HOLDOUT_ACCESSED is False
    assert ML_BASELINE_PRIOR_ROLE == "PROBABILITY_QUALITY_FLOOR"
    assert ML_BASELINE_LINEAR_ROLE == "LEARNED_LINEAR_DISCRIMINATION_REFERENCE"
    assert ML_BASELINE_LINEAR_PRODUCTION_READY is False


def test_phase10_gate8_evidence_separates_discrimination_from_probability_quality() -> None:
    assert ML_BASELINE_LINEAR_WEIGHTED_MACRO_AUC > 0.5
    assert ML_BASELINE_LINEAR_WEIGHTED_LOG_LOSS > ML_BASELINE_PRIOR_WEIGHTED_LOG_LOSS
    assert ML_BASELINE_LINEAR_WEIGHTED_ECE > ML_BASELINE_PRIOR_WEIGHTED_ECE
    assert ML_BASELINE_LINEAR_LOG_LOSS_FOLD_WINS == 0
    assert ML_BASELINE_LINEAR_BRIER_FOLD_WINS == 2
    assert ML_BASELINE_CALIBRATION_DEFERRED_TO_GATE10 is True
    assert ML_GATE9_CANDIDATE_MODEL_BENCHMARK_CURRENT is True
