from packages.ml.label_policy import ML_PREDICTION_LABEL_HORIZON_SESSIONS
from packages.ml.walk_forward_policy import (
    ML_WALK_FORWARD_ACCEPTED_CANDIDATE,
    ML_WALK_FORWARD_ACCEPTED_DISTINCT_TEST_SESSIONS,
    ML_WALK_FORWARD_ACCEPTED_FOLD_COUNT,
    ML_WALK_FORWARD_ACCEPTED_MINIMUM_TRAIN_ROWS,
    ML_WALK_FORWARD_ACCEPTED_TOTAL_TEST_ROWS,
    ML_WALK_FORWARD_ADDITIONAL_EMBARGO_SESSIONS,
    ML_WALK_FORWARD_EXPANDING_TRAIN,
    ML_WALK_FORWARD_FINAL_HOLDOUT_END,
    ML_WALK_FORWARD_FINAL_HOLDOUT_ROWS,
    ML_WALK_FORWARD_FINAL_HOLDOUT_SESSIONS,
    ML_WALK_FORWARD_FINAL_HOLDOUT_START,
    ML_WALK_FORWARD_MINIMUM_TRAIN_SESSIONS,
    ML_WALK_FORWARD_POLICY_ACCEPTED,
    ML_WALK_FORWARD_POLICY_CONTRACT_VERSION,
    ML_WALK_FORWARD_PURGE_SESSIONS,
    ML_WALK_FORWARD_RANDOM_ROW_SPLIT_ALLOWED,
    ML_WALK_FORWARD_STEP_SESSIONS,
    ML_WALK_FORWARD_TEST_SESSIONS,
    ML_WALK_FORWARD_VALIDATION_SESSIONS,
)


def test_phase10_gate7_policy_locks_expanding_quarterly_schedule() -> None:
    assert ML_WALK_FORWARD_POLICY_CONTRACT_VERSION == (
        "ml-walk-forward-policy-v1-expanding-quarterly-252train-purge3-holdout63"
    )
    assert ML_WALK_FORWARD_POLICY_ACCEPTED is True
    assert ML_WALK_FORWARD_ACCEPTED_CANDIDATE == "quarterly-train252"
    assert ML_WALK_FORWARD_EXPANDING_TRAIN is True
    assert ML_WALK_FORWARD_MINIMUM_TRAIN_SESSIONS == 252
    assert ML_WALK_FORWARD_VALIDATION_SESSIONS == 63
    assert ML_WALK_FORWARD_TEST_SESSIONS == 63
    assert ML_WALK_FORWARD_STEP_SESSIONS == 63


def test_phase10_gate7_policy_purges_full_label_horizon_without_random_split() -> None:
    assert ML_PREDICTION_LABEL_HORIZON_SESSIONS == 3
    assert ML_WALK_FORWARD_PURGE_SESSIONS == ML_PREDICTION_LABEL_HORIZON_SESSIONS
    assert ML_WALK_FORWARD_ADDITIONAL_EMBARGO_SESSIONS == 0
    assert ML_WALK_FORWARD_RANDOM_ROW_SPLIT_ALLOWED is False


def test_phase10_gate7_policy_preserves_oos_evidence_and_final_holdout() -> None:
    assert ML_WALK_FORWARD_ACCEPTED_FOLD_COUNT == 10
    assert ML_WALK_FORWARD_ACCEPTED_DISTINCT_TEST_SESSIONS == 630
    assert ML_WALK_FORWARD_ACCEPTED_TOTAL_TEST_ROWS == 3_978_577
    assert ML_WALK_FORWARD_ACCEPTED_MINIMUM_TRAIN_ROWS == 1_448_662
    assert ML_WALK_FORWARD_FINAL_HOLDOUT_SESSIONS == 63
    assert ML_WALK_FORWARD_FINAL_HOLDOUT_START == "2026-05-12"
    assert ML_WALK_FORWARD_FINAL_HOLDOUT_END == "2026-08-11"
    assert ML_WALK_FORWARD_FINAL_HOLDOUT_ROWS == 454_773
