from __future__ import annotations

from packages.ml.final_acceptance_policy import (
    ML_FINAL_ACCEPTANCE_BRIER_IMPROVEMENT_VS_PRIOR,
    ML_FINAL_ACCEPTANCE_GATE12_ARTIFACTS_VERIFIED,
    ML_FINAL_ACCEPTANCE_HOLDOUT_ROWS,
    ML_FINAL_ACCEPTANCE_HOLDOUT_SESSIONS,
    ML_FINAL_ACCEPTANCE_LOG_LOSS_IMPROVEMENT_VS_PRIOR,
    ML_FINAL_ACCEPTANCE_MODEL_BRIER,
    ML_FINAL_ACCEPTANCE_MODEL_LOG_LOSS,
    ML_FINAL_ACCEPTANCE_MODEL_MACRO_AUC,
    ML_FINAL_ACCEPTANCE_MODEL_STATUS,
    ML_FINAL_ACCEPTANCE_POLICY_ACCEPTED,
    ML_FINAL_ACCEPTANCE_POLICY_CONTRACT_VERSION,
    ML_FINAL_ACCEPTANCE_PRIOR_BRIER,
    ML_FINAL_ACCEPTANCE_PRIOR_LOG_LOSS,
    ML_FINAL_ACCEPTANCE_PURGE_SESSIONS,
    ML_FINAL_ACCEPTANCE_REPLAY_MAX_ABS_PROBABILITY_DIFF,
    ML_FINAL_ACCEPTANCE_REPLAY_PASSED,
    ML_FINAL_ACCEPTANCE_TRAINING_ENDPOINTS_IN_HOLDOUT,
    ML_PHASE10_ACCEPTED,
)


def test_phase10_gate13_final_acceptance_policy_is_locked() -> None:
    assert ML_FINAL_ACCEPTANCE_POLICY_CONTRACT_VERSION == (
        "ml-final-acceptance-policy-v1-accepted-2026-08-14-hgb15"
    )
    assert ML_FINAL_ACCEPTANCE_POLICY_ACCEPTED is True
    assert ML_PHASE10_ACCEPTED is True
    assert ML_FINAL_ACCEPTANCE_MODEL_STATUS == "ACCEPTED_PRODUCTION_MODEL"


def test_phase10_gate13_holdout_evidence_passes_locked_thresholds() -> None:
    assert ML_FINAL_ACCEPTANCE_MODEL_LOG_LOSS < ML_FINAL_ACCEPTANCE_PRIOR_LOG_LOSS
    assert ML_FINAL_ACCEPTANCE_MODEL_BRIER < ML_FINAL_ACCEPTANCE_PRIOR_BRIER
    assert ML_FINAL_ACCEPTANCE_MODEL_MACRO_AUC >= 0.52
    assert ML_FINAL_ACCEPTANCE_LOG_LOSS_IMPROVEMENT_VS_PRIOR == 0.01619
    assert ML_FINAL_ACCEPTANCE_BRIER_IMPROVEMENT_VS_PRIOR == 0.01778


def test_phase10_gate13_reproducibility_and_leakage_evidence_is_locked() -> None:
    assert ML_FINAL_ACCEPTANCE_REPLAY_PASSED is True
    assert ML_FINAL_ACCEPTANCE_REPLAY_MAX_ABS_PROBABILITY_DIFF == 0.0
    assert ML_FINAL_ACCEPTANCE_TRAINING_ENDPOINTS_IN_HOLDOUT == 0
    assert ML_FINAL_ACCEPTANCE_GATE12_ARTIFACTS_VERIFIED == 10
    assert len(ML_FINAL_ACCEPTANCE_PURGE_SESSIONS) == 3
    assert ML_FINAL_ACCEPTANCE_HOLDOUT_SESSIONS == 63
    assert ML_FINAL_ACCEPTANCE_HOLDOUT_ROWS == 454_773
