from packages.features.feature_registry import CORE_FEATURE_REGISTRY
from packages.ml.feature_policy import (
    ML_FEATURE_POLICY_ACCEPTED,
    ML_FEATURE_POLICY_CONTRACT_VERSION,
    ML_GATE5_ACCEPTED_CANDIDATE_ROWS,
    ML_GATE5_ACCEPTED_CANDIDATE_SYMBOLS,
    ML_GATE5_BAD_FEATURE_ROWS,
    ML_GATE5_FEATURE_JOIN_ROWS,
    ML_GATE5_MARKET_REGIME_COVERAGE_FRACTION,
    ML_GATE5_MARKET_REGIME_COVERED_ROWS,
    ML_MARKET_REGIME_EVALUATION_CONTEXT_ACCEPTED,
    ML_MARKET_REGIME_MODEL_INPUT_ACCEPTED,
    ML_PRODUCTION_CORE_FEATURE_COUNT,
    ML_PRODUCTION_CORE_FEATURE_NAMES,
    ML_PRODUCTION_FEATURE_PARQUET_UNION_BY_NAME_REQUIRED,
    ML_PRODUCTION_OBSERVATION_AVAILABILITY_RULE,
    ML_SECTOR_REGIME_MODEL_INPUT_ACCEPTED,
    ML_TICKER_REGIME_MODEL_INPUT_ACCEPTED,
)


def test_phase10_gate5_feature_policy_locks_core33_postclose_inputs() -> None:
    assert ML_FEATURE_POLICY_CONTRACT_VERSION == (
        "ml-feature-policy-v1-core33-postclose-regime-context-not-predictor"
    )
    assert ML_FEATURE_POLICY_ACCEPTED is True
    assert ML_PRODUCTION_CORE_FEATURE_COUNT == 33
    assert ML_PRODUCTION_CORE_FEATURE_NAMES == tuple(
        definition.name for definition in CORE_FEATURE_REGISTRY.all()
    )
    assert ML_PRODUCTION_OBSERVATION_AVAILABILITY_RULE == (
        "POST_SESSION_CLOSE_AFTER_DAILY_FEATURE_MATERIALIZATION"
    )
    assert ML_PRODUCTION_FEATURE_PARQUET_UNION_BY_NAME_REQUIRED is True


def test_phase10_gate5_feature_policy_preserves_full_population_integrity() -> None:
    assert ML_GATE5_ACCEPTED_CANDIDATE_ROWS == 6_588_579
    assert ML_GATE5_ACCEPTED_CANDIDATE_SYMBOLS == 12_596
    assert ML_GATE5_FEATURE_JOIN_ROWS == ML_GATE5_ACCEPTED_CANDIDATE_ROWS
    assert ML_GATE5_BAD_FEATURE_ROWS == 0


def test_phase10_gate5_regime_context_is_not_silently_projected_backward() -> None:
    assert ML_GATE5_MARKET_REGIME_COVERED_ROWS == 5_136_676
    assert ML_GATE5_MARKET_REGIME_COVERAGE_FRACTION == (
        ML_GATE5_MARKET_REGIME_COVERED_ROWS / ML_GATE5_ACCEPTED_CANDIDATE_ROWS
    )
    assert ML_MARKET_REGIME_EVALUATION_CONTEXT_ACCEPTED is True
    assert ML_MARKET_REGIME_MODEL_INPUT_ACCEPTED is False
    assert ML_SECTOR_REGIME_MODEL_INPUT_ACCEPTED is False
    assert ML_TICKER_REGIME_MODEL_INPUT_ACCEPTED is False
