from __future__ import annotations

from packages.ml.calibration_policy import (
    ML_CALIBRATION_ACCEPTED_FOLDS,
    ML_CALIBRATION_ACCEPTED_METHOD,
    ML_CALIBRATION_ACCEPTED_MODEL,
    ML_CALIBRATION_ACCEPTED_OOS_ROWS,
    ML_CALIBRATION_FINAL_HOLDOUT_ACCESSED,
    ML_CALIBRATION_ISOTONIC_BRIER,
    ML_CALIBRATION_ISOTONIC_ECE,
    ML_CALIBRATION_ISOTONIC_LOG_LOSS,
    ML_CALIBRATION_PLATT_BRIER,
    ML_CALIBRATION_PLATT_ECE,
    ML_CALIBRATION_PLATT_LOG_LOSS,
    ML_CALIBRATION_POLICY_ACCEPTED,
    ML_CALIBRATION_POLICY_CONTRACT_VERSION,
    ML_CALIBRATION_POSTHOC_ENABLED,
    ML_CALIBRATION_RAW_BRIER,
    ML_CALIBRATION_RAW_ECE,
    ML_CALIBRATION_RAW_LOG_LOSS,
)


def test_phase10_gate10_raw_probability_policy_is_locked() -> None:
    assert ML_CALIBRATION_POLICY_CONTRACT_VERSION == (
        "ml-calibration-policy-v1-raw-no-posthoc-calibration"
    )
    assert ML_CALIBRATION_POLICY_ACCEPTED is True
    assert ML_CALIBRATION_ACCEPTED_METHOD == "raw"
    assert ML_CALIBRATION_POSTHOC_ENABLED is False
    assert ML_CALIBRATION_ACCEPTED_MODEL == "hgb_leaf15_iter100"


def test_phase10_gate10_raw_beats_both_posthoc_candidates_on_probability_quality() -> None:
    assert ML_CALIBRATION_RAW_LOG_LOSS < ML_CALIBRATION_PLATT_LOG_LOSS
    assert ML_CALIBRATION_RAW_LOG_LOSS < ML_CALIBRATION_ISOTONIC_LOG_LOSS
    assert ML_CALIBRATION_RAW_BRIER < ML_CALIBRATION_PLATT_BRIER
    assert ML_CALIBRATION_RAW_BRIER < ML_CALIBRATION_ISOTONIC_BRIER
    assert ML_CALIBRATION_RAW_ECE < ML_CALIBRATION_PLATT_ECE
    assert ML_CALIBRATION_RAW_ECE < ML_CALIBRATION_ISOTONIC_ECE


def test_phase10_gate10_scope_preserves_final_holdout() -> None:
    assert ML_CALIBRATION_ACCEPTED_FOLDS == 10
    assert ML_CALIBRATION_ACCEPTED_OOS_ROWS == 3_978_577
    assert ML_CALIBRATION_FINAL_HOLDOUT_ACCESSED is False
