from __future__ import annotations

from packages.ml.baseline_policy import ML_BASELINE_PRIOR_WEIGHTED_BRIER, ML_BASELINE_PRIOR_WEIGHTED_LOG_LOSS
from packages.ml.candidate_model_policy import (
    ML_CANDIDATE_MODEL_ACCEPTED_BRIER,
    ML_CANDIDATE_MODEL_ACCEPTED_BRIER_FOLD_WINS_VS_PRIOR,
    ML_CANDIDATE_MODEL_ACCEPTED_FOLDS,
    ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS,
    ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS_FOLD_WINS_VS_PRIOR,
    ML_CANDIDATE_MODEL_ACCEPTED_MACRO_AUC,
    ML_CANDIDATE_MODEL_ACCEPTED_MODEL,
    ML_CANDIDATE_MODEL_ACCEPTED_OOS_ROWS,
    ML_CANDIDATE_MODEL_CHALLENGER_BRIER,
    ML_CANDIDATE_MODEL_CHALLENGER_LOG_LOSS,
    ML_CANDIDATE_MODEL_CHALLENGER_MACRO_AUC,
    ML_CANDIDATE_MODEL_FINAL_HOLDOUT_ACCESSED,
    ML_CANDIDATE_MODEL_POLICY_ACCEPTED,
    ML_CANDIDATE_MODEL_POLICY_CONTRACT_VERSION,
    ML_GATE10_CALIBRATION_CURRENT,
)


def test_phase10_gate9_candidate_policy_is_locked() -> None:
    assert ML_CANDIDATE_MODEL_POLICY_CONTRACT_VERSION == (
        "ml-candidate-model-policy-v1-hgb-leaf15-probability-quality-winner"
    )
    assert ML_CANDIDATE_MODEL_POLICY_ACCEPTED is True
    assert ML_CANDIDATE_MODEL_ACCEPTED_MODEL == "hgb_leaf15_iter100"
    assert ML_CANDIDATE_MODEL_ACCEPTED_FOLDS == 10
    assert ML_CANDIDATE_MODEL_ACCEPTED_OOS_ROWS == 3_978_577


def test_phase10_gate9_winner_beats_probability_floor_and_challenger_quality() -> None:
    assert ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS < ML_BASELINE_PRIOR_WEIGHTED_LOG_LOSS
    assert ML_CANDIDATE_MODEL_ACCEPTED_BRIER < ML_BASELINE_PRIOR_WEIGHTED_BRIER
    assert ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS < ML_CANDIDATE_MODEL_CHALLENGER_LOG_LOSS
    assert ML_CANDIDATE_MODEL_ACCEPTED_BRIER < ML_CANDIDATE_MODEL_CHALLENGER_BRIER
    assert ML_CANDIDATE_MODEL_CHALLENGER_MACRO_AUC > ML_CANDIDATE_MODEL_ACCEPTED_MACRO_AUC
    assert ML_CANDIDATE_MODEL_ACCEPTED_LOG_LOSS_FOLD_WINS_VS_PRIOR == 10
    assert ML_CANDIDATE_MODEL_ACCEPTED_BRIER_FOLD_WINS_VS_PRIOR == 10


def test_phase10_gate9_preserves_final_holdout_and_advances_to_calibration() -> None:
    assert ML_CANDIDATE_MODEL_FINAL_HOLDOUT_ACCESSED is False
    assert ML_GATE10_CALIBRATION_CURRENT is True
